### ISSUE TITLE
Fake \pdfoutput keyword

### ISSUE THREAD

**Issue by pkgw** [tectonic-typesetting/tectonic#10]
Files from Overleaf have this embedded but it seems that XeTeX doesn't.

**Comment by pkgw** [comment]
@guillochon Ditto, mind emailing me a test case?

**Comment by pkgw** [comment]
Whoops; this was one that @mnicholl encountered.

**Comment by pkgw** [comment]
This turns out to be much more challenging than I first thought, since to implement this correctly we need to add `pdfoutput` as a new internal integer variable. That process involves recalculating all of the magic hardcoded offsets that are embedded in the C code. It's worthwhile to fix that stuff, so I'm working on it, but it's a tedious process. Especially since if I get anything wrong, I could easily break the engine in subtle ways.

**Comment by khaledhosny** [comment]
I don’t think faking `\pdfoutput` is really a good idea, it is a pdftex primitive and some TeX/LaTeX code might use it to detect if it is running under pdftex or not.

**Comment by pkgw** [comment]
Great to see a comment from you, @khaledhosny ! I know that XeTeX represents a lot of your effort -- I hope you feel that this fork gives adequate credit to the XeTeX team.

I have the same worry about adding `\pdfoutput`, but it has been a stumbling block for some of my beta testers so I am planning to try adding it and seeing if any problems arise. Tectonic is still very much in beta so I will be comfortable​ removing it if it turns out to be more trouble than it's worth.

**Comment by pkgw** [comment]
Ok @mnicholl it took three months of work but this feature will show up in version 0.1.4.
