### ISSUE TITLE
maketitle not working as expected

### ISSUE THREAD

**Issue by Peter-Ibrahim** [tectonic-typesetting/tectonic#1004]
I have this simple file where I test it `\documentclass{article}
\title{Here}
\author{Me}
\begin{document}
  \maketitle
  Hello there
\end{document}
`
I get this output

Running TeX ...
Fontconfig error: Cannot load default config file: No such file: (null)
warning: test.tex:5: Overfull \hbox (1494.78418pt too wide) in paragraph at lines 5--5
Rerunning TeX because "test.aux" changed ...
warning: test.tex:5: Overfull \hbox (1494.78418pt too wide) in paragraph at lines 5--5
warning: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Running xdvipdfmx ...
Writing `.\test.log` (2.42 KiB)
error: File ended prematurely

Content inside logs
**
(test.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-02-24> (article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(size10.clo
File: size10.clo 2021/10/04 v1.4n Standard LaTeX file (size option)
)
\c@part=\count181
\c@section=\count182
\c@subsection=\count183
\c@subsubsection=\count184
\c@paragraph=\count185
\c@subparagraph=\count186
\c@figure=\count187
\c@table=\count188
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen138
) (l3backend-xetex.def
File: l3backend-xetex.def 2022-02-07 L3 backend support: XeTeX
\c__kernel_sys_dvipdfmx_version_int=\count189
\l__color_backend_stack_int=\count190
\g__color_backend_stack_int=\count191
\g__graphics_track_int=\count192
\l__pdf_internal_box=\box50
\g__pdf_backend_object_int=\count193
\g__pdf_backend_annotation_int=\count194
\g__pdf_backend_link_int=\count195
) (test.aux)
\openout1 = `test.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 4.
LaTeX Font Info:    Trying to load font information for TS1+cmr on input line 4
.
 (ts1cmr.fd
File: ts1cmr.fd 2019/12/16 v2.5j Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

Overfull \hbox (1494.78418pt too wide) in paragraph at lines 5--5
 \TU/lmr/m/n/17.28 Here 
 []

LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <12> on input line 5.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <8> on input line 5.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <6> on input line 5.
[1

] (test.aux) )
Output written on test.xdv (1 page, 848 bytes).

I tried using `\usepackage[T1]{fontsetup}` and `\usepackage[T1]{fontenc}` and they work. Is this expected behavior or a problem with my setup? I am on Windows 11 21H2 build 22000.1516, I do not remember having this problem about a month ago on my previous windows 10 machine

**Comment by mnrvwl** [comment]
Interesting! I'm not able to reproduce this on Linux, macOS or Windows 11, all under `arm64`. I get the initial `Fontconfig error`, but the document compiles fine. Running Windows 11 `22H2 22621.1265` here.

**Comment by Neved4** [comment]
Hi @Peter-Ibrahim, any news on this?

**Comment by mikemykhaylov** [comment]
I can repro it on macOS 13.6.9 with `tectonic v0.15`, even without the `maketitle` typeseting a document errors out
