### ISSUE TITLE
LaTeX Font Warning: Font shape `TU/cmr/bx/n' undefined -- using TU/cmr/m/n instead

### ISSUE THREAD

**Issue by dartacao** [tectonic-typesetting/tectonic#1011]
I have an issue with a class I'm using, that I'm not really managing to suss out. When compiling a document with this class, it uses specific `\section`, `\subsection` and so on fonts. These are defined like so:

```tex
\def\sectionfont{\fontsize{10}{12}\bfseries\boldmath\rightskip2pc plus1fill{}}
\def\subsectionfont{\fontsize{10}{12}\bfseries\boldmath\itshape\rightskip2pc plus1fill{}}
\def\subsubsectionfont{\fontsize{10}{12}\itshape\rightskip2pc plus1fill{}}
```
However, when compiling with tectonic, the compiled document is not using the correct font and I get these warnings in the log file:
```tex
LaTeX Font Warning: Font shape `TU/cmr/bx/n' undefined
(Font)              using `TU/cmr/m/n' instead on input line 53.

LaTeX Font Info:    Trying to load font information for U+msa on input line 53.
```
Is this a known issue? Does it have a known solution?

**Comment by kpym** [comment]
This is not tectonic specific proble. You can google about ``Font shape `TU/cmr/bx/n' undefined`` and see that tis is is due to Latin Modern lacking boldface small caps.

**Comment by dartacao** [comment]
I see what you mean, and managed to solve it by installing cmu roman and manually specifying it with \fontspec. However, this is not due to small caps issues (the font shape it's looking for is /bx/n which maps to a normal type, not /sc which is small caps. I have googled it extensively, to no success though, and had to dredge through a few dozen pages. It's not a tectonic issue, though, that is correct.
