### ISSUE TITLE
ß (eszet) can become "SS" depending upon `fontenc` settings

### ISSUE THREAD

**Issue by kulp** [tectonic-typesetting/tectonic#1026]
This might be related to #992.

I discovered tectonic recently and I like it a lot.

I found the following example does not work the way I expected coming from `pdflatex`. In particular, the "ß" (eszet) character turns into "SS" when `\usepackage[...]{fontenc}` (for at least `T1` and `OT2`) is in play.

I would like `tectonic` to be able to produce [the result that overleaf.com produces for this file (with "ß")](https://github.com/tectonic-typesetting/tectonic/files/11291684/Strasse-bad.pdf), instead of [the result that I actually get (with "SS")](https://github.com/tectonic-typesetting/tectonic/files/11291682/Strasse-good.pdf), while leaving the `fontenc` line in play, or using something equivalent; removing the `fontenc` line in my project results in major aesthetic changes that I have not investigated yet.

(Despite the ß, I am not writing German; the eszet is incidental, and is extracted automatically from a list of mostly-English tune titles.)

```latex
\documentclass{article}

% Without the next line relating to `fontenc`, the undesired translation of `ß`
% into `SS` does not occur. However, removing this line yields other
% unacceptable problems.
\usepackage[T1]{fontenc}

\begin{document}

If the two words look alike, there is a bug.

Straße
StraSSe

\end{document}
```

I understand that tectonic comes from XeTeX, and I have used mainly lualatex and pdflatex up to this point; maybe this is somehow expected behavior. I welcome any education.

**Comment by kpym** [comment]
This is not a `tectonic` specific problem. 

If you are working with `xelatex` (`tectonic`) or `lualatex` you should use `fontspec` instead of `fontenc`. If you want to create documents for all these comilers you can use the following snippet.

```latex
% --------------- PDFLaTeX, XeLaTeX or LuaLaTeX ?
\usepackage{iftex}
\ifPDFTeX
  % --------------- PDFLaTeX or LaTeX
  \usepackage[utf8]{inputenc}
  \usepackage[T1]{fontenc}
  \usepackage{lmodern}
\else
  % --------------- XeLaTeX, tectonic or LuaLaTeX
  \usepackage{fontspec}
\fi
% ---------------
```

**Remarks**.
- This is not a problem but a question, so IMO this topic should be moved to the [discussions](https://github.com/tectonic-typesetting/tectonic/discussions) forum 🙏.
- For questions like this, Google, [Stack Exchange](https://tex.stackexchange.com/) and ChatGPT can be asked first 🙂.

**Comment by kulp** [comment]
@kpym Thanks for the quick response. Your snippet solves my problem nicely.

I did ask my search engine several times about tectonic differences relating to `fontspec`, but perhaps it would have been more fruitful to ask it about XeTeX instead. I will try to remember that Discussions exists too. One learns something every day.

**Comment by kulp** [comment]
> Your snippet solves my problem nicely.

I was wrong; it just gets me back to the other "aesthetic changes that I have not investigated yet". Nevertheless now I have a better idea what to ask about in a different forum. Merci quand même.
