### ISSUE TITLE
v2: `compile` preamble/postamble support

### ISSUE THREAD

**Issue by mangkoran** [tectonic-typesetting/tectonic#1048]
First of all, thank you for making such amazing tools! I am pretty new to Latex and Tectonic make it easy for me to compile Latex docs.

I have a question regarding `tectonic -X compile`. As Tectonic defaults to include pre- and postamble .tex files, how can I make standalone document compiled using `compile` to include pre- and postamble? My case is that I split my documents using `subfiles`.

**Comment by xinslu** [comment]
Just like regular latex you can use `\input{filename}` or `\include{filename}`. To import the contents of the file and render them. Hope this solves your issue!
