### ISSUE TITLE
linux-aarch64 build on conda-forge

### ISSUE THREAD

**Issue by MilesCranmer** [tectonic-typesetting/tectonic#1073]
Hi @pkgw,

I was wondering if you might be able to enable the linux-aarch64 build on conda-forge? My use-case is building things inside a docker container on my M1 MacBook, where there does not currently seem to be a binary available on conda. 

My current workaround is to use docker's `--platform=linux/amd64` but this is obviously quite a bit slower.

This might just be a call like so:
```
@conda-forge-admin, please add linux-aarch64
```
on the feedstock repository, but I'm not sure if this service is set up or not. It might need to be added manually.

Thanks!
Miles

**Comment by pkgw** [comment]
Sure thing! See:

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4735

which will set up the automation that should get us there.

I'm going to close this issue in favor of that PR. It's not a big deal either way, but if you have other issues relating to the conda-forge package, a better place to file them would be directly on the `conda-forge/tectonic-feedstock` repo.

**Comment by pkgw** [comment]
Here's the migrator PR: https://github.com/conda-forge/tectonic-feedstock/pull/67

**Comment by pkgw** [comment]
It took me a bit longer than expected to get the cross-arch builds to fully work, but I just merged the above PR, so they should be available starting in a few hours.

**Comment by MilesCranmer** [comment]
Awesome. Thanks!
