### ISSUE TITLE
Continuous Compile?

### ISSUE THREAD

**Issue by DieracDelta** [tectonic-typesetting/tectonic#1082]
Is there an equivalent option to latexmk's `-interaction=nonstopmode` option? Not seeing anything in the cli help menu, but entirely possible I'm missing something.

**Comment by CraftSpider** [comment]
I think you may be looking for `-X watch`? It will recompile the document on every file change.

**Comment by pkgw** [comment]
And if you mean specifically `nonstopmode` for interaction during a single compile, that is the mode that Tectonic *always* uses during a compile, no matter what the user or the document tries to set. Tectonic will never stop to prompt the user for input.

**Comment by DieracDelta** [comment]
Ah, thank you!
