### ISSUE TITLE
[Feature request] allow user to specify CTAN bundles fallbacks

### ISSUE THREAD

**Issue by Dzordzu** [tectonic-typesetting/tectonic#1087]
## Related issues
* https://github.com/tectonic-typesetting/tectonic/issues/685#issuecomment-826325275
* https://github.com/tectonic-typesetting/tectonic/issues/221#issuecomment-416452195
* #484 
* #965
* #1086 

## What's the current state
No option to download missing bundles from any fallback resource

## How to fix it
Add a special option to the V2 cli that will add a fallback URLs if the files are missing during a build 

## Discussion
 #1088

**Comment by rm-dr** [comment]
Closing this for now. A big part of tectonic is reproducibility, and automatic downloads from texlive directly counteracts this goal.

If you need files that are not bundled, include them in your workspace and use the `extra_paths` key.
