### ISSUE TITLE
Fix breaking vertical space in `fancyhdr`

### ISSUE THREAD

**Issue by Neved4** [tectonic-typesetting/tectonic#1110]
While accommodating around _≈27K lines of LaTeX_ I was greeted by an ominous:

```awk
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
error: tfg.tex:10: LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.10 \end{document}
                   
No pages of output.
Transcript written on tfg.log.
error: halted on potentially-recoverable error as specified
```

So after much reversing and taming the beast, I stumbled upon the offending code: a line break with extra vertical space.

#### MWE

```latex
\documentclass{article}

\RequirePackage{fancyhdr}
  \fancyfoot[C]{\\[2ex] foo}
                % ^ replace \\[2ex] with \vspace{2ex} to make it compile
\begin{document}
  \pagestyle{fancy}
  bar
\end{document}
```

The code works on `pdfTeX`/`XeTeX`/`LuaTeX` as of `TeX Live 2023`. It doesn't under current `tectonic`. Could be due to something in TeX Live that'll get naturally resolved with the upgrade to 2023. Using `\vspace` instead just works. Not a high priority, but it was a strange find.

**Comment by rm-dr** [comment]
I'm surprised that's valid LaTeX. `\\[2ex]` just looks... Wrong.

I just tested this, and it seems that this isn't a tectonic problem. It's a TeXlive 2022 problem, which doesn't seem to support that odd macro. I tried building with my TeXlive 2023 bundle, and everything worked.

This will work once [this](https://github.com/tectonic-typesetting/tectonic-texlive-bundles/issues/12) is resolved and a TeXlive 2023 bundle is published.
