### ISSUE TITLE
"invalid gzip header" when trying to reach network bundle

### ISSUE THREAD

**Issue by KenanSulayman** [tectonic-typesetting/tectonic#113]
```
note: this is a BETA release; report issues at https://github.com/tectonic-typesetting/tectonic/issues
note: indexing http://purl.org/net/pkgwpub/tectonic-default
note: resolved to https://akamai.bintray.com/59/59eecf9d49e259191ef66cb68b274c7c50fa20a75f593130d2603176418422eb?__gda__=exp=1499122780~hmac=7dc2a6a6aec2977cc02dee650295fa52eaa694f39c19e61e85b326598aafd0a6&response-content-disposition=attachment%3Bfilename%3D%22tlextras-2016.0r4.tar%22&response-content-type=application%2Fx-tar&requestInfo=U2FsdGVkX18yLaB1xCSymVW06Kv3ik02M3hVcUeEVcxvSYnCX_pnSVf20xmhUUpSaKMz6IiwtdUM8al9SGHbJZLhWxxRqwoF02ubNwgpeouEn_t7te0Th5wXQEtNYkrpKD5xPWo5FrUZ61DJLaO26Q
error: invalid gzip header
```

Is there a way to work around this?

**Comment by pkgw** [comment]
Hmm, this is certainly not what is supposed to happen! I suspect that your networking setup is preventing Tectonic from downloading the file correctly — maybe you were behind a captive portal that proxied HTTP requests or something. In particular, the `resolved to` line should tell you something like:

```
note: resolved to https://dl.bintray.com/pkgw/tectonic/tl2016extras/2016.0r4/tlextras-2016.0r4.tar
```

Can you reproduce this problem reliably? Does it happen even if you connect to the internet from different locations and/or using different methods?

**Comment by raphiz** [comment]
I still have this issue with Tectonic 0.1.6. I posted the output of running  `curl -v -L https://purl.org/net/pkgwpub/tectonic-default` into a [Gist](https://gist.github.com/raphiz/4b38da871198ba7d50db42bd3e1c5ff8) - seems to be similar to the results that @Mrmaxmeier posted in #114.
My current workaround is to override the URL via the configuration file as mentioned in [a comment on #59](https://github.com/tectonic-typesetting/tectonic/issues/59/#issuecomment-305938033).

**Comment by Mrmaxmeier** [comment]
@raphiz Sorry to bother - are you sure you're running Tectonic 0.1.6?
The request flow in your curl log should be handled by #114.
Are you getting the same `tectonic` output as @KenanSulayman?

**Comment by raphiz** [comment]
@Mrmaxmeier Yes, I'm running Tectonic 0.1.6:
```
docker run -ti --rm fabianhauser/tectonic:0.1.6 --version
Tectonic 0.1.6
```
I have Tectonic installed locally as well as in a Docker container, and the issue does occur in both cases. However, I can't reproduce it deterministically.
But if it occurs, the output is the same as posted by @KenanSulayman.
Anyways, I suggest we keep this issue closed, and if someone else should get the same issue we can investigate further.
