### ISSUE TITLE
brigde_harfbuzz macOS build error when running cargo install --path

### ISSUE THREAD

**Issue by mhuttner** [tectonic-typesetting/tectonic#1156]
My local build fails when i try to run "cargo install" for tectonic on macOS aarch64
Somehow the harfbuzz folder is not created (with the latest version of harfbuzz).

Uncommenting this line fixes the issue: 
https://github.com/tectonic-typesetting/tectonic/blob/cf443a7ffa1dbc9400c5d110f30f89e7717da7d8/crates/bridge_harfbuzz/build.rs#L136-L138

**Comment by pkgw** [comment]
It looks like we should then change that code to try to create the directory, and ignore the error if it already exists. Would you be in a position to submit a pull request to that effect?
