### ISSUE TITLE
Expired SSL certificate?

### ISSUE THREAD

**Issue by Julrob199** [tectonic-typesetting/tectonic#1208]
Hello, 

I get an error, when I try to run tectonic main.tex:

I also disabled my pihole and vpn to see, if they are causing this error. But no. Everything else on the internet is working fine. Has the ssl server certificate be  renewed?

tectonic main.tex
note: connecting to https://relay.fullyjustified.net/default_bundle_v33.tar
error: error sending request for url (https://relay.fullyjustified.net/default_bundle_v33.tar): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091: (self-signed certificate)
caused by: error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091: (self-signed certificate)
caused by: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091: (self-signed certificate)
caused by: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:

**Comment by Julrob199** [comment]
I saw that it was me, who had the problem. In tor it opens the page. So I guess, this is part of a configuration problem?

**Comment by rm-dr** [comment]
See #1188. Not fixed yet.
