### ISSUE TITLE
Intermediate `.snm` files left around when processing Beamer files

### ISSUE THREAD

**Issue by pkgw** [tectonic-typesetting/tectonic#121]
As reported by teras [on the forum](https://tectonic.newton.cx/t/minor-bug-with-snm-files/49):

> I have a minor issue. I am using beamer and when I use the \label command, there is some garbage left, namely a file with an .snm extension. Since all other intermediate files are gone (hurray!), I believe this file should be gone too.

It should not be hard to devise a simple test case here.

**Comment by teras** [comment]
Yes, the test case is rather trivial - as a bonus a .toc file is also left behind.

```
\documentclass{beamer}
\begin{document}
\frame{ \label{hello} }
\end{document}
```
