### ISSUE TITLE
Revtex 4.2 Issue

### ISSUE THREAD

**Issue by hughesjs** [tectonic-typesetting/tectonic#1214]
Tectonic doesn't seem to work with RevTex 2.4 (needed for APS journals). I'm unable to compile the sample document contained in the attached zip at `doc/latex/revtex/sample/aps`.
[revtex-tds-2023-05-30.zip](https://github.com/user-attachments/files/16900233/revtex-tds-2023-05-30.zip). I've been using `tectonix -X compile`.

It seems to hang on:
> Running BibTeX on apssamp.aux ...

I've also tried building this minimal example and for some reason it throws an undefined control sequence error on the `\author` line.

```latex
\documentclass[%
 reprint
 amsmath,amssymb,
 aps
]{revtex4-2}

\title{My Title}

\author{Me}
\affiliation{My Affiliation}

\maketitle

\begin{document}


Hello, world.
\end{document}

``` 

Any ideas?

**Comment by hughesjs** [comment]
Strangely the template, rather than the sample does seem to compile, so I'm not actually sure where the issue is. I'm unblocked for now so this isn't too urgent but it's probably worth looking into?

**Comment by hughesjs** [comment]
Oh wait, I've seen what I did...

**Comment by xiaoxuan-yu** [comment]
I'm using tectonic to compile the aip sample of revtex and I'm facing the same issue. I mean it hangs on bibtex step. Is it possible to share how did you solved the problem?
