### ISSUE TITLE
inputs in Tectonic.toml not working

### ISSUE THREAD

**Issue by jerrywcy** [tectonic-typesetting/tectonic#1217]
I configured my Tectonic.toml according to described in the [Tectonic book](https://tectonic-typesetting.github.io/book/latest/ref/tectonic-toml.html), but when I run `tectonic -X build`, I received the following error:

```bash
$ tectonic -X build
note: "version 2" Tectonic command-line interface activated
error: TOML parse error at line 8, column 1
  |
8 | inputs = ["_preamble.tex", "llm.tex", "_postamble.tex"]
  | ^^^^^^
unknown field `inputs`, expected one of `name`, `type`, `tex_format`, `preamble`, `index`, `postamble`, `shell_escape`, `shell_escape_cwd`
```

Sample `Tectonic.toml`:

```toml
[[output]]
name = "llm"
type = "pdf"
inputs = ["_preamble.tex", "llm.tex", "_postamble.tex"]
```

My tectonic version:
```bash
$ tectonic -X --version
Tectonic 0.15.0tectonic -X 0.15.0
```

But in the Tectonic book it said that preamble, index and postamble are deprecated options. Is something wrong on the Tectonic book or do I need to upgrade the version to follow main? Anything I can do to solve this problem?

**Comment by rm-dr** [comment]
Whoops, the book is in the future. Input arrays were implemented [Feb 15](https://github.com/tectonic-typesetting/tectonic/commit/7432afd5d8ee25075ff085f7314d37492ee0ae1b), but 0.15 was released Feb 4. Sorry for the misleading docs.

You could either...
- build tectonic from `master` yourself
- or wait for @pkgw to release a new version.
