### ISSUE TITLE
Plan for HTML output

### ISSUE THREAD

**Issue by bfirsh** [tectonic-typesetting/tectonic#123]
Hi @pkgw! 

LaTeX to HTML is of interest to me. All of the existing things are terrible. I figure something decent needs to be built from scratch, and Tectonic caught my eye as one of the few bits of modern LaTeX work going on.

I noticed in the [HN thread about this](https://news.ycombinator.com/item?id=14450448) and in various issues you mention HTML output as a long-term goal. What are your plans for this? How were you thinking of implementing it? E.g. would it be at the parse tree level or something higher-level?

It's something I'm enthusiastic to make happen, but I'm not sure where to start contributing.

**Comment by pkgw** [comment]
Hi @bfirsh (and, I infer, @demurgos),

Sorry for the extremely long lag in the response time here. I had high hopes for pushing forward on the HTML output front but real life has completely swamped my ability to push things forward.

I wrote up [a brief outline of HTML plans on the forums site](https://tectonic.newton.cx/t/a-brief-outline-of-the-plan-for-html-support/57). Please continue the discussion there if you have any questions! (I do feel that that sort of discussion belongs on a website more like the forums than the GitHub issues pages.)

Unfortunately I'm not optimistic for having more time again any time soon, but we'll see ... Tectonic is doing great for my day-to-day PDF-creation needs, but a huge reason that I started the project was the HTML stuff.

Peter
