### ISSUE TITLE
PURL setup link has expired SSL certificate

### ISSUE THREAD

**Issue by ghost** [tectonic-typesetting/tectonic#131]
Technically not a bug in tectonic, but thought I should let you know.

```
note: indexing https://purl.org/net/pkgwpub/tectonic-default
error: The OpenSSL library reported an error: The OpenSSL library reported an error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264:
```

**Comment by siddhanathan** [comment]
Never mind. Fixed on their end.

**Comment by demurgos** [comment]
I still get an error when navigating to their website: https://purl.org/net/pkgwpub/tectonic-default

Tectonic fails, I also checked with Firefox (using Linux if it matters).

**Comment by demurgos** [comment]
I just retried: it seems fine for me. I believe that it was due to cache.

**Comment by pkgw** [comment]
Thanks for pursuing this. If the SSL cert is working again for multiple people I think it's likely that PURL has fixed their problem, so I think this can be closed again.

**Comment by pkgw** [comment]
Nope, now I'm seeing this. Grr.

**Comment by demurgos** [comment]
I can confirm I get this error too. The certificate I get expires on 2017-11-05.

**Comment by pkgw** [comment]
I've created a [forum thread](https://tectonic.newton.cx/t/problems-caused-by-expired-ssl-certificate-for-purl-org/75) pointing to a workaround.

**Comment by ilovezfs** [comment]
@pkgw this is happening again. Cert expired 4 Jan 2018

**Comment by pkgw** [comment]
Seems to be fixed again, so I guess I'll close this again ... if this problem persists we'll need to switch to another URL-redirection service, though.

**Comment by Arvedui** [comment]
> The certificate expired on November 1, 2018, 11:55:08 PM GMT+0.

It is happening *again* …

**Comment by pkgw** [comment]
ARGH. Thanks for the heads-up.

**Comment by PHPirates** [comment]
The [bintray link](https://dl.bintray.com/pkgw/tectonic/tl2016extras/2016.0r4/tlextras-2016.0r4.tar) from the [workaround](https://tectonic.newton.cx/t/how-to-use-tectonic-if-you-can-t-access-purl-org/44) you linked to seems not valid anymore, any new workaround link and does it still work?

**Comment by pkgw** [comment]
The suggested workaround link is: https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar (We were having problems with Bintray too — fun!)

OK, does anyone know of a redirection service that we could switch to instead of purl.org? Requirements:

- Reliable, long-lived service
- SSL
- Can redirect via status code 302
- The redirect destination can be updated over time

**Comment by pkgw** [comment]
Well, here's *a* list of PURL services: https://sites.google.com/site/persistenturls/purls-in-the-wild

**Comment by pkgw** [comment]
Although, I think this is fixed again. @Arvedui @PHPirates do you agree?

**Comment by PHPirates** [comment]
@pkgw Thanks, if the issue persists I'll try the workaround unless you have it fixed soon. I just tried and I still have the same problem, see https://travis-ci.org/PHPirates/travis-ci-latex-pdf/jobs/449807724

**Comment by pkgw** [comment]
@PHPirates Yes, you're right. Depending on what URL you type into a browser, it can sometimes work, but this consistently fails for me:

```
$ wget https://purl.org/net/pkgwpub/tectonic-default
--2018-11-02 10:03:38--  https://purl.org/net/pkgwpub/tectonic-default
Resolving purl.org (purl.org)... 207.241.224.2
Connecting to purl.org (purl.org)|207.241.224.2|:443... connected.
ERROR: The certificate of ‘purl.org’ is not trusted.
ERROR: The certificate of ‘purl.org’ has expired.
The certificate has expired
```

I did manage to get in direct contact with some people at archive.org last time, so I've reached out again. Hopefully they'll straighten it out quickly.

**Comment by rodluger** [comment]
As a temporary workaround I found that switching from `https` to `http` by setting the `config.toml` file to

```
[[default_bundles]]
url = "http://purl.org/net/pkgwpub/tectonic-default"
```

according to the [workaround](https://tectonic.newton.cx/t/how-to-use-tectonic-if-you-can-t-access-purl-org/44) did the trick. But probably not a good long-term solution.

**Comment by Arvedui** [comment]
@pkgw 
I still get the expired certificate.

**Comment by Arvedui** [comment]
@rodluger 
switching to http might not be acceptable for everyone

**Comment by PHPirates** [comment]
Since I still had the problem, I tested that the workaround works for me:
```bash
sudo mkdir -p ~/.config/Tectonic/
echo "[[default_bundles]]" | sudo tee --append ~/.config/Tectonic/config.toml
sudo echo "url = \"https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar\"" | sudo tee --append ~/.config/Tectonic/config.toml
```

@pkgw I see you merged a fix, are you going to release a new Tectonic soon? If not I would copy this workaround to my build setups everywhere.

**Comment by WtfJoke** [comment]
Would be great if you could release a bugfix-release for this. 
Something like 0.1.10.1 or 0.1.11

**Comment by pkgw** [comment]
PR in flight — lucky [#256](https://github.com/tectonic-typesetting/tectonic/pull/256).

**Comment by pkgw** [comment]
OK, version 0.1.11 is out in the world. *Hopefully* I have updated the Arch Linux package right such that it will magically update when the master-branch CI finishes, too!
