### ISSUE TITLE
Cargo install fails because of texlive

### ISSUE THREAD

**Issue by ivegotasthma** [tectonic-typesetting/tectonic#132]
Just ran `cargo install texlive`

```
[asthma@dev ~]$ cargo install texlive
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: could not find `texlive` in registry `https://github.com/rust-lang/crates.io-index`
```

**Comment by pkgw** [comment]
Why are you trying to install a crate named `texlive`? To get Tectonic, it should be `tectonic` ...

**Comment by pkgw** [comment]
Feel free to open an issue if there's anywhere on the website or other docs that could have clarified things for you.
