### ISSUE TITLE
libicuuc.so.59 not found

### ISSUE THREAD

**Issue by demurgos** [tectonic-typesetting/tectonic#138]
Hi,
I installed tectonic for Linux from [AUR](https://aur.archlinux.org/packages/tectonic/) (for Arch) a few months ago.
I updated my system this week, and I cannot use tectonic anymore due to the following error:

```
$ tectonic --version
tectonic: error while loading shared libraries: libicuuc.so.59: cannot open shared object file: No such file or directory
```

The package on AUR downloads the release 0.15 from github and builds it locally. I manually changed the file to download and build the latest version (0.17) but still have the error.

**Comment by demurgos** [comment]
Here are the libraries I have:
```
$ ls /lib/libicuuc.so*
/lib/libicuuc.so  /lib/libicuuc.so.60  /lib/libicuuc.so.60.1
```

How can I configure tectonic to use this new version?

**Comment by demurgos** [comment]
This feels like a dirty hack, but I solved it with the following command:
```
sudo ln -s /lib/libicuuc.so /lib/libicuuc.so.59
```

**Comment by pkgw** [comment]
CC @alexander-bauer 

I think the AUR for Tectonic is not updating properly. I'm not an Arch user so I'm not the best person to investigate, but *hopefully* this won't be too tough to fix.

**Comment by folkvir** [comment]
I reached the same problem today but wuth the version 60

```bash
=> tectonic --version
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.60.dylib
  Referenced from: /usr/local/bin/tectonic
  Reason: image not found
Abort trap: 6
```

`ls /usr/lib | grep libicuuc`, 0 result.

Env: 
```bash
=> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202
```

**Comment by demurgos** [comment]
I have the same issue today with the version 62. How can I fix it manually? This issue occurs quite often on Arch since it's always using the latest available versions.

**Comment by pkgw** [comment]
For a local workaround, unfortunately I'm not sure if there's a better near-term solution than making a symlink as you suggested earlier.

More systematically, I don't believe there's any better solution than having the maintainer(s) of the Arch package create new builds when dependencies update their versions in this way. I am not sure of the best way to ping the maintainer(s) for an update, or if there's any kind of system that can automatically identify when updates will be needed.

The other thing is that I doubt that the binary compatibility of the ICU libraries is *actually* changing this rapidly — my guess is that the library versions are being increased more frequently than strictly necessary. But it would take investigation to figure out where those version bumps are coming from are coordination to try to do a better job of avoiding them when not necessary.

**Comment by demurgos** [comment]
I finally found the root cause of my issue.
I had multiple Tectonic versions: compiled it myself, built from AUR and installed using `cargo`. It messed with my path and used old versions. I made sure to clean everything and just use the AUR version. Everything works fine now.

**Comment by pkgw** [comment]
Ah, glad to hear there is a straightforward solution! And hopefully the binary compatibility is being more stable and I thought.
