### ISSUE TITLE
Option to emit .ps instead of .pdf

### ISSUE THREAD

**Issue by kozross** [tectonic-typesetting/tectonic#155]
It'd be nice to be able to produce PostScript files instead of PDF - I just got this request from my PhD supervisor, but couldn't use Tectonic because I couldn't see an option to do this.

**Comment by pkgw** [comment]
I think this is one that essentially can't happen within Tectonic. The PDF document model is a superset of PostScript in several ways (color model, embedding other PDFs) and the Tectonic processing model expects to take advantage of those possibilities. It wouldn't be impossible to implement a conversion after the fact, but it would just be reproducing the functionality of external tools. So I'd recommend using Tectonic to create a PDF, then using one of those external tools to convert. [This StackExchange thread](https://stackoverflow.com/questions/3403485/pdf-to-ps-conversion) names some options, and a quick Google seems to suggest that there are many others.
