### ISSUE TITLE
Location of installed LaTeX packages for caching

### ISSUE THREAD

**Issue by PHPirates** [tectonic-typesetting/tectonic#159]
This is a support question, I have tried asking on the [forum](https://tectonic.newton.cx/t/location-of-installed-latex-packages-for-caching-ci/97) but with no response so trying here.

I am using miniconda with tectonic for continuous integration which works awesome, but installing the LaTeX packages every time takes a long time and is like the only disadvantage I found (besides that makeindex is not included, see #115 ). I have successfully cached miniconda, however tectonic still installs all LaTeX packages on every run - I would like to cache those as well.

**Question**
Which folder do I need to include my cache such that the LaTeX packages are retained and tectonic recognizes that?

I am now using, to install tectonic on the linux server,
```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
bash miniconda.sh -b -p $HOME/miniconda -u;
conda config --add channels conda-forge;
conda config --set always_yes yes;
conda update --all;
conda install tectonic;
```
and caching `$HOME/miniconda`.

To compare, when using TeX Live was sufficient to cache `TEXDIR=/tmp/texlive` and `$HOME/.texlive`.

My full setup is [here](https://github.com/PHPirates/travis-ci-latex-pdf) , referencing issue PHPirates/travis-ci-latex-pdf#3

**Comment by wopian** [comment]
Tectonic's cache is in `$HOME/.cache/Tectonic`

**Comment by PHPirates** [comment]
@wopian wow thanks for the quick response, I ran the tests and it works! Build time down from five minutes to one. Awesome!

**Comment by pkgw** [comment]
@PHPirates Sorry for not replying on the forum! Thanks for your patience.

**Comment by s-weigand** [comment]
Since this was referenced in the Forum, for macOS the path is `~/Library/Caches/Tectonic`

**Comment by s-weigand** [comment]
And as another reference, on Windows it is `%LOCALAPPDATA%/TectonicProject/Tectonic`.
And yes forward slashes are also allowed on Windows 😉.
