### ISSUE TITLE
Remove dependency on "md5" crate

### ISSUE THREAD

**Issue by pkgw** [tectonic-typesetting/tectonic#16]
We should use rust-crypto for this, since we need that crate for SHA256 sums anyway.

**Comment by musoke** [comment]
I'll make an attempt at this in a couple days.

**Comment by pkgw** [comment]
Fantastic, thanks!

**Comment by pkgw** [comment]
By the way, please get in touch with me if you have any problems building or understanding the source layout. Things are still not as “plug-and-play” as I'd like just yet.

**Comment by musoke** [comment]
Will do
