### ISSUE TITLE
Gibberish in the front matter when using biblatex

### ISSUE THREAD

**Issue by jongwook** [tectonic-typesetting/tectonic#164]
I'm using Tectonic and Travis CI to automatically build PDF files and upload it to Github Pages [(project link)](https://github.com/jongwook/dissertation/blob/master/.travis.yml).

Unlike the output in the local editor, Tectonic's output contains gibberish words filling 5 pages before the cover page:

![image](https://user-images.githubusercontent.com/266841/36776389-97ba4458-1c33-11e8-9ce0-0912916f7922.png)

It's hard to isolate the source of problem as it's a large project, but the broken words are coming from the bibtex records.

I'm using `biblatex` with `bibtex` backend, at the moment.

**Comment by jongwook** [comment]
I confirm that the problem goes away if I don't use `biblatex` and use the old-style `\bibliography`.

**Comment by pkgw** [comment]
That is not surprising in a sense. Tectonic only knows about `bibtex` right now, and it is confirmed to have problems with documents that use `biblatex`. We still don't have a strategy for how to deal with `biblatex` but the engine should at least produce an error for documents that it can't handle. If you have the chance to create a minimal example that demonstrates the problem, that would be very helpful. Or if you're comfortable sharing the document source with me, I can try to develop a minimal example myself.

**Comment by jongwook** [comment]
@pkgw I've made a minimal example that reproduces this error: [here](https://github.com/jongwook/tectonic-biblatex-issue/blob/jibberish/main.pdf)

The same package has another tag [`long_url_error`](https://github.com/jongwook/tectonic-biblatex-issue/blob/long-url-error/library.bib#L15) where `bibtex` fails to process a citation with `url` field longer than about 70 characters. That happens when the url is long enough to make two `\verb` commands in the `.bbl` file, and according to this [SO question](https://tex.stackexchange.com/questions/311426/bibliography-error-use-of-blxbblverbaddi-doesnt-match-its-definition-ve) it should have been fixed in the latest biblatex.

**Comment by mnrvwl** [comment]
Hey @jongwook I'm happy to bring the news that your [MWE](https://github.com/jongwook/tectonic-biblatex-issue) is giving proper output!
You can use any of `bibtex` or `biber` biblatex backends under `tectonic 0.11.0` as of now 🎉

Would you give it a try and let me know if it works for you? Thx 💜

**Comment by jongwook** [comment]
@mnrvwl Indeed it works! It's long been since I completed the dissertation in question, but it's a wonder of open source. Thank you so much for the news!

**Comment by pkgw** [comment]
Thanks for the followup @mnrvwl and confirmation @jongwook!
