### ISSUE TITLE
Can't use make dyld: Library not

### ISSUE THREAD

**Issue by bioinfo24091** [tectonic-typesetting/tectonic#167]
im working on MACos 10.13.3

After running `Brew doctor` and it suggested me to remove some files actually to many directories so i removed it all. and reinstall all of it again and their dependencies.

unfortunately i have end up with an error i cant run `make` any more and compile any program , the word by itself its not recognised by the system any more

i have seen some solutions around but non worked out please advice

```

mimis-Mac-Pro:~ mohanad$ make
dyld: Library not loaded: /usr/local/lib/libintl.8.dylib
  Referenced from: /usr/local/bin/make
  Reason: image not found
Abort trap: 6
```

**Comment by pkgw** [comment]
Hi,

Did you report this against the right repository? I don't see what this report has to do with the Tectonic program. I am not a Homebrew user so I'm afraid I don't have any advice off the top of my head.

Regards,

Peter
