### ISSUE TITLE
The underlying stream reported an error: Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by peterjc** [tectonic-typesetting/tectonic#168]
Trying to use tectonic as an alternative to ``pfdlatex`` on Linux,

```
$ conda install tectonic
...
$ tectonic --version
Tectonic 0.1.7
$ tectonic Tutorial.tex
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
note: indexing https://purl.org/net/pkgwpub/tectonic-default
error: The underlying stream reported an error: The underlying stream reported an error: Connection reset by peer (os error 104)
caused by: The underlying stream reported an error: The underlying stream reported an error: Connection reset by peer (os error 104)
caused by: The underlying stream reported an error: Connection reset by peer (os error 104)
caused by: Connection reset by peer (os error 104)
```

It appears to be an SSL issue which is not being handled that gracefully:

```
$ curl https://purl.org/net/pkgwpub/tectonic-default
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to purl.org:443 
$ wget https://purl.org/net/pkgwpub/tectonic-default
--2018-04-09 14:14:49--  https://purl.org/net/pkgwpub/tectonic-default
Resolving purl.org... 207.241.224.2
Connecting to purl.org|207.241.224.2|:443... connected.
Unable to establish SSL connection.
```

Likewise I can't access the HTTPS address from my browser, but on HTTP this shows up as blocked by my employer's firewall...

Doing a little digging, https://archive.org/services/purl/purl/net/pkgwpub/tectonic-default and https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator were interesting.

I can access this via alternative domains ``purl.oclc.org``, ``purl.com`` and ``purl.net``

```
$ curl https://purl.oclc.org/net/pkgwpub/tectonic-default
<!DOCTYPE HTML>
<html>
<head>
<title>302 Found</title>
</head>
<body>
<h1>Found</h1>
<p>The resource requested is available <a href="https://dl.bintray.com/pkgw/tectonic/tl2016extras/2016.0r4/tlextras-2016.0r4.tar">here</a>.<p>
</body>
</html>
```

Is is worth adding some fallback domains in case of similar web-blocking for other users? e.g. Try in order:

* purl.org
* purl.com
* purl.net
* purl.oclc.org

**Comment by pkgw** [comment]
The *hope* was that one purl.org URL would be robust enough to always Just Work, but it has not worked out that way in practice. So, yes, I think it is time to think about fallbacks.

It's very helpful to learn that `purl.oclc.org` works since OCLC is the organization that now maintains PURLs and I suspect that a URL that is connected to their primary website will be more reliable than the standalone `purl.org` one.

**Comment by peterjc** [comment]
According to https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator

> OCLC are now redirecting DNS requests for purl.oclc.org to purl.org.

But it may nevertheless be a more reliable top level domain name in years to come.
