### ISSUE TITLE
Some problem with CM slanted font

### ISSUE THREAD

**Issue by pkgw** [tectonic-typesetting/tectonic#17]
Seen in one of my sample files, no time to investigate right now. Relevant bits:

```
\usepackage[bf, font={small,sl}]{caption}
```

Leading to:

```
<use  "lcs.pdf" > <use  "lcs.pdf" >
! Font OT1/cmr/m/sl/10.95=cmsl10 at 10.95pt not loadable: Metric (TFM) file or installed font not found.
<to be read again> 
                   relax 
l.32 ...0.5]{lcs}{Yadda yadda here is some stuff.}
```

But the relevant `cmsl10` files seem to be found in the bundle.

**Comment by pkgw** [comment]
The problem does *not* emerge if I ask for just `small` or just `sl` in the options to the `caption` package.

**Comment by khaledhosny** [comment]
Do you actually have `cmsl10.tfm` file where kpathsea (or its replacement) can find?

**Comment by pkgw** [comment]
Yes, I think that all of the necessarily files are included in the bundle:

```
?rw-------  2.0 unx     3833 b- defN 17-Mar-13 11:17 cmsl10.mf
?rw-------  2.0 unx     1305 b- defN 17-Mar-13 11:18 cmsl10.pfm
?rw-------  2.0 unx    35022 b- defN 17-Mar-13 11:18 cmsl10.pfb
?rw-------  2.0 unx    13512 b- defN 17-Mar-13 11:18 cmsl10.pk
?rw-------  2.0 unx     1508 b- defN 17-Mar-13 11:18 cmsl10.tfm
?rw-------  2.0 unx    10207 b- defN 17-Mar-13 11:18 cmsl10.afm
```

**Comment by khaledhosny** [comment]
I thought you use kpathsea, but checking the code and it is no where to be seen. Sorry for the noise.

**Comment by pkgw** [comment]
No worries! Yes, the big first stage of Tectonic was removing kpathsea in as many places as possible, so that I could use a more flexible system with pluggable I/O backends instead. (Of course this *could* be accomplished without removing kpathsea, but in the model that I am trying to work in, kpathsea becomes unnecessary.)

**Comment by pkgw** [comment]
Does not reproduce in the latest development version.

**Comment by viatcheslavmogilevsky** [comment]
I see similar issue for 0.1.5 
```
Font T2A/cmr/m/n/10=larm1000 at 10.0pt not loadable: Metric (TFM) file or ins
talled font not found.
```

**Comment by viatcheslavmogilevsky** [comment]
I just commented out `\usepackage[T2A]{fontenc}` and it works well.
I was trying using T2A package to include Cyrillic characters, but this .tex file doesn't need them.

**Comment by pkgw** [comment]
OK, @viatcheslavmogilevsky I think that means that the current default bundle (`tlextras` version `2016.0r4`) does not include the `larm1000` font. Please open a separate issue if this becomes a limitation.
