### ISSUE TITLE
User feedback when trying to use Unicode without necessary fonts

### ISSUE THREAD

**Issue by shak-mar** [tectonic-typesetting/tectonic#173]
With these contents in a file `test.tex`:
```
\documentclass{article}

\usepackage[utf8]{inputenc}

\begin{document}
Störende Heißluft
\end{document}
```
When I run `tectonic test.tex`, the output pdf says "Strende Heiluft".  To make sure, I also tried `latex test.tex; xdvipdfmx test.dvi`, and that result says "Störende Heißluft", as expected.

The output of `tectonic --version` is `Tectonic 0.1.7`. Any other output I should paste?

**Comment by shak-mar** [comment]
Without the `\usepackage` line, it still only says "Strende Heiluft".

**Comment by shak-mar** [comment]
(I composed this before you wrote that last comment:)

If I run `xelatex test.tex`, with or without the `\usepackage` line, it works: "Störende Heißluft". But the version of xelatex I used to try this seems to be different from what tectonic uses.  Output of `xelatex test.tex`:
```
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2017-04-15>
Babel <3.15> and hyphenation patterns for 22 language(s) loaded.
(/opt/texlive/2017/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/opt/texlive/2017/texmf-dist/tex/latex/base/size10.clo)) (./test.aux) [1]
(./test.aux) )
Output written on test.pdf (1 page).
Transcript written on test.log.
```

Output of `tectonic test.tex -p`:
```
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
(test.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(size10.clo)) (test.aux) [1] (test.aux) )
(see the transcript file for additional information)
Output written on test.xdv (1 page, 236 bytes).
Transcript written on test.log.
note: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Running xdvipdfmx ...
[1]
Writing test.pdf (2539 bytes)
Skipped writing 1 intermediate files (use --keep-intermediates to keep them)
```

**Comment by shak-mar** [comment]
Yes! Adding `\usepackage{fontspec}` fixes the issue for me.  For reference, here's the full example now:
```
\documentclass{article}

\usepackage{fontspec}

\begin{document}
Störende Heißluft
\end{document}
```
Thanks!

**Comment by pkgw** [comment]
OK. I'm going to repurpose this issue to be about the user experience: if someone is doing what you initially tried, there should be some feedback suggesting that fontspec be loaded.

**Comment by pkgw** [comment]
Note to self: the right place to do this might be the `char_warning` function. If you set `\tracinglostchars=2`, this function will log warnings about missing characters that get triggered appropriately for the example document at the top of this issue.
