### ISSUE TITLE
Tectonic is now available in MacPorts! (update website to say so)

### ISSUE THREAD

**Issue by l2dy** [tectonic-typesetting/tectonic#183]
FYI, I've added Tectonic to [MacPorts](https://www.macports.org/) in https://github.com/macports/macports-ports/commit/a0205d23ed4de9fcff66338c4e13c53a54a64610, so with MacPorts installed one can install Tectonic with `sudo port install tectonic` on macOS.

**Comment by pkgw** [comment]
Great! Can I talk you into a submitting a PR for the [website](https://github.com/tectonic-typesetting/tectonic-typesetting.github.io) to mention this on the installation page? I can totally do it myself if you don't feel like it, but the more different people submit PRs to Tectonic repos, the happier I am.

**Comment by pkgw** [comment]
:+1:
