### ISSUE TITLE
Distribute a static build

### ISSUE THREAD

**Issue by malbarbo** [tectonic-typesetting/tectonic#185]
I know what you're thinking: it's easier said than done!

But I did it! I built a static version of tectonic! It toke a lot of time, but the final patches are really small.

I used the following docker alpine container to do the build:

```Dockerfile
FROM alpine:edge

RUN apk update && \
    apk upgrade && \
    apk add \
        g++ \
        git \
        rust \
        cargo \
        fontconfig-dev \
        freetype-static \
        glib-static \
        graphite2-dev \
        graphite2-static \
        harfbuzz-dev \
        harfbuzz-static \
        icu-dev \
        icu-static \
        openssl-dev \
        zlib-dev

ENV TECTONIC_STATIC=1
ENV PKG_CONFIG_ALL_STATIC=1
ENV OPENSSL_STATIC=1
ENV OPENSSL_DIR=/usr
ENV RUSTFLAGS="-C target-feature=+crt-static"

RUN mkdir /out/

CMD git clone https://github.com/malbarbo/tectonic --branch static && \
    cd tectonic && \
    sed -i -e 's/AES_cbc_encrypt/AES_cbc_encrypt2/g' \
              ./tectonic/dpx-dpxcrypt.h \
              ./tectonic/dpx-pdfencrypt.c \
              ./tectonic/dpx-dpxcrypt.c && \
    cargo build --release && \
    cp target/release/tectonic /out/
```

```
docker build . -t tectonic
docker run -v $(pwd):/out tectonic
```

The image install the requirements including [static](https://github.com/alpinelinux/aports/pulls?q=is%3Apr+author%3Amalbarbo) version of the libs.

The env vars indicates to `tectonic`, `pkg-config` and `openssl` packages and `rustc` to do a static build.

The rename of `AES_cbc_encrypt` to `AES_cbc_encrypt2` is to avoid duplicate symbol between tectonic and openssl.

The following [changes](
https://github.com/tectonic-typesetting/tectonic/compare/master...malbarbo:static) to tectonic are needed:

- disable `serde_derive` (it [does not work](https://github.com/rust-lang/cargo/issues/5266) with static musl build). The changes disable loading config, so the final patch needs another approach, maybe implementing `Deserialize`
- add `TECTONIC_STATIC` as an option to `build.rs` to static link `stdc++`
- use a [`pkg-config-rs`](https://github.com/alexcrichton/pkg-config-rs/compare/master...malbarbo:allow-sys-static) crate that allows static linking system libraries

I can no longer work on it, but I would be glad if anyone could move on from here and add a static builder to travis.

**Comment by malbarbo** [comment]
For the curious, the static build have 50MB and 35MB stripped.

**Comment by pkgw** [comment]
An update: I've upgraded the Travis infrastructure so that it is a bit more thinkable to generate static binaries on CI and upload them to GitHub releases — see [the new driver script](https://github.com/tectonic-typesetting/tectonic/blob/master/dist/travis.sh) for some context.

**Comment by efx** [comment]
This looks great!
@malbarbo have you been able to work on this with the new driver script @pkgw mentioned? If not I can help complete this task.

**Comment by malbarbo** [comment]
@efx it would be great if you could complete the task!

**Comment by efx** [comment]
I also noticed the work in #420 which could be applicable as well; as I get some "free time" I'll investigate that work compared with the above approach.

**Comment by malbarbo** [comment]
Now we have a static build! Thanks @pkgw.
