### ISSUE TITLE
cannot install or build tectonic

### ISSUE THREAD

**Issue by kaizengliu** [tectonic-typesetting/tectonic#199]
when `cargo install tectnoic` or `cargo build`, get error as following:

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "." "-I" "/home/less/IdeaProjects/tectonic/target/debug/build/tectonic-ab19c26fd83db5db/out" "-I" "/usr/include/freetype2" "-I" "/usr/include/harfbuzz" "-I" "/usr/include/x86_64-linux-gnu" "-I" "/usr/include/freetype2" "-I" "/usr/include/libpng12" "-Wall" "-Wextra" "-Wall" "-Wcast-qual" "-Wdate-time" "-Wendif-labels" "-Wextra" "-Wformat=2" "-Winit-self" "-Wlogical-op" "-Wmissing-declarations" "-Wmissing-include-dirs" "-Wmissing-prototypes" "-Wnested-externs" "-Wold-style-definition" "-Wpointer-arith" "-Wredundant-decls" "-Wstrict-prototypes" "-Wsuggest-attribute=format" "-Wswitch-bool" "-Wundef" "-Wwrite-strings" "-Wno-unused-parameter" "-Wno-implicit-fallthrough" "-Wno-sign-compare" "-std=gnu11" "-DHAVE_ZLIB=1" "-DHAVE_ZLIB_COMPRESS2=1" "-DZLIB_CONST=1" "-o" "/home/less/IdeaProjects/tectonic/target/debug/build/tectonic-ab19c26fd83db5db/out/tectonic/core-bridge.o" "-c" "tectonic/core-bridge.c" with args "cc" did not execute successfully (status code exit code: 1).

**Comment by pkgw** [comment]
There should be an error message from the actual C compiler that appears higher up in the output of the `cargo build`  command. Usually it is delimited by the text `error:` Can you find that message?

**Comment by kaizengliu** [comment]
Yes, the error messge is as following:

cargo:warning=In file included from tectonic/xetexd.h:11:0,
cargo:warning=                 from tectonic/core-bridge.c:15:
cargo:warning=tectonic/XeTeXOTMath.h:43:5: error: unknown type name ‘hb_ot_math_glyph_part_t’
cargo:warning=     hb_ot_math_glyph_part_t *parts;
cargo:warning=     ^
cargo:warning=cc1: warning: unrecognized command line option ‘-Wno-implicit-fallthrough’
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "." "-I" "/home/less/IdeaProjects/tectonic/target/debug/build/tectonic-ab19c26fd83db5db/out" "-I" "/usr/include/freetype2" "-I" "/usr/include/harfbuzz" "-I" "/usr/include/x86_64-linux-gnu" "-I" "/usr/include/freetype2" "-I" "/usr/include/libpng12" "-Wall" "-Wextra" "-Wall" "-Wcast-qual" "-Wdate-time" "-Wendif-labels" "-Wextra" "-Wformat=2" "-Winit-self" "-Wlogical-op" "-Wmissing-declarations" "-Wmissing-include-dirs" "-Wmissing-prototypes" "-Wnested-externs" "-Wold-style-definition" "-Wpointer-arith" "-Wredundant-decls" "-Wstrict-prototypes" "-Wsuggest-attribute=format" "-Wswitch-bool" "-Wundef" "-Wwrite-strings" "-Wno-unused-parameter" "-Wno-implicit-fallthrough" "-Wno-sign-compare" "-std=gnu11" "-DHAVE_ZLIB=1" "-DHAVE_ZLIB_COMPRESS2=1" "-DZLIB_CONST=1" "-o" "/home/less/IdeaProjects/tectonic/target/debug/build/tectonic-ab19c26fd83db5db/out/tectonic/core-bridge.o" "-c" "tectonic/core-bridge.c" with args "cc" did not execute successfully (status code exit code: 1).

**Comment by pkgw** [comment]
Ah, OK. You need a newer version of the [harfbuzz](https://www.freedesktop.org/wiki/Software/HarfBuzz/) library. However, the build scripts should catch this and give a clearer error message. Can you tell me what version of Harfbuzz you have installed?

**Comment by kaizengliu** [comment]
Yes, the version of  harfuzz is 1.0.1 ( `pkg-config  --modversion  harfbuzz`  get 1.0.1), quite a old version. The newest should be 1.8.x, but `apt install libharfbuzz-dev` get the 1.0.1. Maybe I need build harfuzz from the source directly.
