### ISSUE TITLE
Use RustCrypto crates instead of rust-crypto

### ISSUE THREAD

**Issue by newpavlov** [tectonic-typesetting/tectonic#20]
rust-crypto is no longer [maintained](https://github.com/DaGenix/rust-crypto/pulls). [RustCrypto](https://github.com/RustCrypto) organization aims to succeed it.

Additionally it also provides algorithms divided into separate crates united by the same traits, so you no longer need to pull the whole library just for two hashes.

For your project you can just use `md-5` and `sha2` crates. I can create a draft PR, but I can't check if I made all necessary changes, as unfortunately I get compilation [error](https://gist.github.com/newpavlov/c90e3edfca69fdafda643e86ecfa0a3a) on my system.

**Comment by pkgw** [comment]
Hmmm, is there really no more output from the compilation stage? It looks like the C compiler invocation is failing, but usually that ought to involve some error messages and whatnot. Do you not even have a C compiler installed on the relevant machine?

**Comment by newpavlov** [comment]
I get bunch of warning without clear error. Full output of `RUST_BACKTRACE=1 cargo build` can be seen [here](https://gist.github.com/newpavlov/292203cbb2e54d0eff47d3a922ab2857). Exit status 256 strange too, shouldn't it have a negative status in case of an error?

**Comment by pkgw** [comment]
Ah, [this line](https://gist.github.com/newpavlov/292203cbb2e54d0eff47d3a922ab2857#file-gistfile1-txt-L2053) shows the key error. It is not an error that I've seen before.

What OS / Linux distro / etc are you using to try to build the project? What version?

**Comment by newpavlov** [comment]
Ubuntu 14.04, `libpng` version is `1.2.50-1ubuntu2.14.04.2`.

**Comment by pkgw** [comment]
OK, I can get Tectonic to build on 14.04 as of commit 0dd1873. Does it work for you now?

**Comment by newpavlov** [comment]
Yes, now it compiles without problems! I've created a PR with the discussed changes.

**Comment by pkgw** [comment]
Merged ⇒ issue fixed. Thanks!
