### ISSUE TITLE
Missing package `color.sty`

### ISSUE THREAD

**Issue by terrybrashaw** [tectonic-typesetting/tectonic#201]
Version: Tectonic 0.1.8

I'm new to LaTeX and haven't used any other engine besides tectonic, so perhaps I'm missing something obvious.

I want to color some text and found multiple resources saying I needed a package to do so. https://ctan.org/pkg/color looks like what I need, and it says it's "Con­tained in TeXLive as `graphics`."

I figured since Tectonic is "powered by TeXLive," `graphics`, and by extension `color`, should be included by default and should be usable from Tectonic. But this doesn't work; tectonic complains of a missing `color.sty`.

**Comment by pkgw** [comment]
This should definitely be possible and has definitely worked for users in the past. Does `\usepackage{graphicx}` work for you?

If not, what is the exact error message? The site that's been hosting the resource files (Bintray) seems to have been rate-limiting requests recently, so the problem might be unrelated to the particular packages you're trying to use.

**Comment by terrybrashaw** [comment]
Both `\usepackage{graphicx}` and `\usepackage{color}` work now.

Unfortunately I don't have the exact error message in my console anymore. If I run into this issue again I'll be sure to save the output.
