### ISSUE TITLE
Figure out why test `tex-outputs:the_letter_a` fails on AppVeyor.

### ISSUE THREAD

**Issue by pkgw** [tectonic-typesetting/tectonic#244]
It just started erroring out because the observed PDF output doesn't match the expected one. If I build Tectonic myself, using either the GNU or the MSVC toolchains, the test works fine. WTF? The test isn't "special" so I'm just going to disable it on Windows, but it would be good to understand what the heck is going on here.

**Comment by crlf0710** [comment]
Maybe check whether git treat the log and other files as text and whether git checkout it in CRLF or LF line ending?

**Comment by pkgw** [comment]
Good idea! But the test used to work, and I have trouble seeing how that behavior would have changed recently ... on the other hand, something relatively weird must be going on, since I feel like my investigations have eliminated any relatively straightforward causes.

One thing that has made this annoying to debug is that I can't gain access to the files generated during the AppVeyor run, which would at least reveal why the files differ. The next step for investigation might be to temporarily hack the test code to have it print out the file contents so that they can be compared.

**Comment by pkgw** [comment]
<shrug>
