### ISSUE TITLE
conda-forge update to 0.1.11

### ISSUE THREAD

**Issue by tzipperle** [tectonic-typesetting/tectonic#264]
Hello,
are there any reasons why the new version 0.1.11 is not deployed to conda-forge?

**Comment by pkgw** [comment]
No good ones! I just lost track of the PR. [Please follow it here if you're interested](https://github.com/conda-forge/tectonic-feedstock/pull/14). There seems to be some CI failure that I need to investigate, but  there shouldn't be anything that needs major work to fix.

**Comment by tzipperle** [comment]
Thanks
