### ISSUE TITLE
A wrapper for Ruby

### ISSUE THREAD

**Issue by xtaniguchimasaya** [tectonic-typesetting/tectonic#281]
I made a wrapper of the Rust API for ruby. We can use it in Ruby, like followings!
1. Run `gem specific_install -l 'git://github.com/xtaniguchimasaya/tectonic-ruby.git'`
    Gem will also download and install tectonic, like Conda. In the feature, I will upload this package to rubygems.org, then we can install with `gem install tectonic`.
2. We can call the Rust API in Ruby.
```ruby
require 'tectonic'
latex = <<-EOS
\usepackage{article}
\begin{document}
Hello, Tectonic!
\end{document}
EOS
pdf = Tectonic.latex_to_pdf(latex)
```

The reason why I made it, is that I'd like to compose editing softwares (LaTeX, Asciidoctor-LaTeX, Asciidoctor-bibtex) into one environment with `bundler` as same as `conda create -n doc shpinx tectonic`. That environment provides one process from RestructuredText to PDF via LaTeX. In the same way, This environment provides one process from Asciidoc to PDF via LaTeX.
I'd like to propose this gem to be official library in the `tectonic-typesetting` organization. It means we move this project to `https://github.com/tectonic-typesetting/tectonic-ruby` if you accept. Of course, then I change the parameters of this gem to this organization.

Thank you.

**Comment by pkgw** [comment]
Yes, this would be wonderful! Thank you for your interest.

I think the best way to do this would be to "transfer" your repository to the Tectonic organization, because that way the one here will be the "main" version rather than a fork, I think. Do you agree?

 [Here is GitHub's documentation](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) on the process. I will need to temporarily give you repository creation rights on the tectonic-typesetting organization before this can work.

**Comment by xtaniguchimasaya** [comment]
Totally okay. However, you said that some packages are managed in `/dist` of this one repository. It looks like [monorepo](https://en.wikipedia.org/wiki/Monorepo) style. The wrapper is independed from the Rust code unlike #280 . So there is no matter of confricts to any work of the repository. I can send pull request soon if you prefer the style.

**Comment by xtaniguchimasaya** [comment]
Now I finish the ready to move my repository to your organization.
- [x] Travis CI
- [x] Gemspec
- [x] LICENSE

https://github.com/xtaniguchimasaya/tectonic-ruby

Could you grant me to transfer my repository?

**Comment by pkgw** [comment]
OK, you should have an invitation now, and I believe it will grant you the necessary privileges. Please let me know if that's not the case!

**Comment by xtaniguchimasaya** [comment]
Thank you. I complete to transfer my repository, and I start to add new tests for the library, with refering #284
