### ISSUE TITLE
Export latex_to_pdf as C API.

### ISSUE THREAD

**Issue by ta2gch** [tectonic-typesetting/tectonic#291]
I think that the tectonic should export some functions to C because It takes a long time to build own library to call from other language like Ruby. C API installed in System makes the build instruction to be easy without cargo. For instance, `tectonic-ruby` requires cargo to install this, but by this proposal, when users install tectonic with homebrew, gem build only glue c code like other ruby library. That reduces a bored time to wait for the finish. 

In my repository forked from this repository has C API with these code.

```toml
# Cargo.toml
[lib]
name = "tectonic"
crate-type = ["cdylib", "rlib"]
```

```rust
// src/lib.rs
#[no_mangle]
pub fn compile(c_latex: *const libc::c_char, c_pdf: *mut u8) -> () {
    unsafe {
        std::ffi::CStr::from_ptr(c_latex).to_str().ok().map(|latex| {
            latex_to_pdf(latex).ok().map(|pdf| {
                let len = pdf.capacity();
                std::ptr::copy_nonoverlapping(pdf.into_boxed_slice().as_ptr(), c_pdf, len);
            })
        });
    }
}
```
 
I don't have the best solution to return the product to C from Rust, this code needs to the enough memory space to contain PDF with `malloc` before calling. 

How do you think? Thank you.

**Comment by pkgw** [comment]
You might be interested in pull request #246 by @Mrmaxmeier! I believe that the goal of his work is to expose this sort of API in a nice structured way ... although I have not looked at his work carefully yet, since it's marked as work-in-progress.

**Comment by ta2gch** [comment]
I see. I'm deeply interested in the pull request #246. I'm looking forward to the finish of his work because his work seams to solve this issue. I keep to seeing the progress. Thank you for telling me.
