### ISSUE TITLE
Include babel language packs in default bundle

### ISSUE THREAD

**Issue by malbarbo** [tectonic-typesetting/tectonic#30]
The following tex file

```tex
\documentclass{article}
\usepackage[brazil]{babel}

\begin{document}
\end{document}
```

produces this error:

```text
note: this is a BETA release; report issues at https://github.com/tectonic-typesetting/tectonic/issues
Running TeX ...
error: something bad happened inside TeX; its output follows:

===============================================================================
(a.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 3 language(s) loaded.
(article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(size10.clo)) (babel.sty

! Package babel Error: Unknown option `brazil'. Either you misspelled it
(babel)                or the language definition file brazil.ldf was not found
.

See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.310 \ProcessOptions*
                      
No pages of output.
Transcript written on a.log.
===============================================================================

error: halted on potentially-recoverable error as specified
```

changing brazil to english produces another (unrelated issue, I think) this error:

```text
note: this is a BETA release; report issues at https://github.com/tectonic-typesetting/tectonic/issues
Running TeX ...
Rerunning TeX because "a.aux" changed ...
Running xdvipdfmx ...
error: cannot open "a.xdv"
```

Note that in a preview execution `english.ldf` was download, but none brazil related file was.

**Comment by malbarbo** [comment]
Oh, by the way, this is an amazing project! Thank you!

**Comment by pkgw** [comment]
Thanks for reporting! It looks as if the `brazil` problem is mainly that the language isn't included in the "bundle" file. I will check it out with `english` to see if there are any other problems.

In the meantime, if you know how to get your hands on the missing files, things should work if you place them in the directory in which you're running Tectonic. Hopefully there aren't too many files that are needed ...

**Comment by malbarbo** [comment]
I copied portuges.ldf from my tex installation (brazil is an alias to portuges) and it changed the error to `error: cannot open "a.xdv"` the same for english. Do you have any idea about this other issue?

**Comment by pkgw** [comment]
Oh! It's just that your document is totally empty. In that case, no XDV file is produced at all. If you add an text after `\begin{document}` I think it will be fine. I suppose this could get filed as a UX bug.

**Comment by malbarbo** [comment]
You are right. This was my minimal example case to reproduce the issue... With my original article it worked just fine! Thanks.

**Comment by pkgw** [comment]
OK, in that case, I think the problem is just that it would be helpful to include language packs in the default bundle — relevant code is [here in the "staging" repository](https://github.com/tectonic-typesetting/tectonic-staging/blob/master/staging.sh#L146).
