### ISSUE TITLE
Figure out how to deal with input documents outside of the current directory

### ISSUE THREAD

**Issue by Ohjeah** [tectonic-typesetting/tectonic#31]
Assuming this structure

```
|_tex
   |_ main.tex
   |_ content
      |_ 1.tex
```

and `main.tex` contains `\include{content/1.tex}` you need to call tectonic from within the tex directory.
If you call it like `tectonic tex/main.tex` you get an error:

> ! LaTeX Error: File `misc/header.tex' not found.

Would be nice to have an `--inplace` option which always sets the working directory to the directory of your main.tex, i.e. `tectonic tex/main.tex --inplace` would be valid.

**Comment by pkgw** [comment]
Ah, good catch. As much as possible I would like to have Tectonic just Do The Right Thing™ without needing special options, so I will think about whether there's a way to get it to work without needing an option. At first blush maybe it would be reasonable to *always* act as if the proposed `--inplace` was active?

**Comment by Ohjeah** [comment]
Yes that would be perfect. I cannot think of a case were you'd want it other way around.

**Comment by pkgw** [comment]
CC @skrat.

**Comment by skrat** [comment]
@pkgw did you find the codes that assume CWD = parentDir(root.tex) ?

**Comment by rekka** [comment]
Is anyone working on this?
