### ISSUE TITLE
Getting "couldn't probe https://archive.org/services/purl/net/pkgwpub/tectonic-default"

### ISSUE THREAD

**Issue by gozzarda** [tectonic-typesetting/tectonic#326]
The bundle link now 404s, which is preventing tectonic from loading any packages.

**Comment by bendem** [comment]
same issue, just downloaded tectonic, it doesn't do anything. Guess I'm back to good old xetex and makefiles

**Comment by bendem** [comment]
As per #131, adding `-w https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.ta` works.

**Comment by pkgw** [comment]
Just got a chance to look at this and it's not clear to me what's going on here. Other folks see that the PURL domain exists, right?

https://archive.org/services/purl/domain/net_pkgwpub

But if I try the link given above or the classic purl.org location, https://purl.org/net/pkgwpub/tectonic-default , I get 404s.

I'll try to contact the Internet Archive folks, although unfortunately I have always found that to be difficult, and I have a lot on my plate at work so I won't be able to tackle this immediately.

**Comment by gozzarda** [comment]
Ah... I have just noticed that tectonic is trying to hit https://archive.org/services/purl/net/pkgwpub/tectonic-default, which is coming up as not found, while the page you linked directs to https://archive.org/services/purl/purl/net/pkgwpub/tectonic-default.

The difference is subtle, but the second contains /purl/purl/ while the first only has one copy. Could it be that archive.org moved the endpoint slightly?

**Comment by bendem** [comment]
I have to say moving the endpoint of a service providing persistent urls is kind of ironic...

**Comment by pkgw** [comment]
Indeed, it would be. The `purl/purl` URLs don't 404, but they don't redirect to the right destinations either. I have yet to find a version of the URL that still works.

Is anyone able to find PURLs that *do* work? Here's a listing of everything in the big `/net` prefix:

https://archive.org/services/purl/domain_search?q=net&page=5

I think maybe just the PURL service got broken over the weekend.

**Comment by pkgw** [comment]
I think my theory was correct, because I think that the download links are working again. Can anyone confirm?

**Comment by gozzarda** [comment]
Can confirm! All looks good from here.

**Comment by arnavs** [comment]
I'm seeing this error again. There's a server error at this link.

**Comment by pkgw** [comment]
@arnavs It looks like you caught things during a [planned maintenance period](https://twitter.com/internetarchive/status/1133925244438106112) from the Internet Archive. Sorry for the inconvenience!

**Comment by arnavs** [comment]
No problem, thanks for letting me know.
