### ISSUE TITLE
fontspec error: "font-not-found"

### ISSUE THREAD

**Issue by dschuessler** [tectonic-typesetting/tectonic#372]
This project compiles just fine with MacTex 2018 and the command `pdflatex thesis.tex`: https://github.com/mbredel/thesis-template

With `tectonic thesis.tex` I get the following error:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "TeX Gyre Pagella" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................
```

**Comment by spl** [comment]
Does `xelatex thesis.tex` give you the same error? If so, you may be able to search for solutions to the problem using `xelatex` (part of [XeTeX](https://en.wikipedia.org/wiki/XeTeX)). Tectonic is a fork of XeTeX, so it often has the same issues.

**Comment by pkgw** [comment]
As an initial guess, though, at the moment Tectonic can only identify fonts based on their filenames, not their symbolic names. So if somewhere you specify a font as "TeX Gyre Pagella", specifying it as `texgyrepagella-regular.otf` might work instead.

Here are the commands I use to load up the TeX Gyre fonts:

```tex
\usepackage{fontspec}%
\newfontfeature{Microtype}{protrusion=default;expansion=default;}%
\setmainfont{texgyrepagella-regular.otf}[%
  Microtype,
  Ligatures = TeX,
  BoldFont = texgyrepagella-bold.otf,
  ItalicFont = texgyrepagella-italic.otf,
  BoldItalicFont = texgyrepagella-bolditalic.otf,
]%

\usepackage{unicode-math}%
\setmathfont{texgyrepagella-math.otf}%
```

(But I know there are ways to specify the font type and abbreviate the font base in `\setmainfont` that can make the setup more compact.)

**Comment by dschuessler** [comment]
You were both right. The error is the same with `xelatex` and replacing all the font's symbolic names with their filenames makes `tectonic` compile the project.

Is addressing this ticket within the scope of tectonic or shall I close this?

**Comment by pkgw** [comment]
OK, I'm glad you were able to work around the problem! I'm actually a bit surprised that `xelatex` didn't give you the same error, since it should have better support for loading fonts by their symbolic names.

Anyway, there are certainly ways in which the Tectonic experience could be improved in this arena, but I'll close this particular issue. Thanks for reporting!

**Comment by timClicks** [comment]
I was just snagged by this issue. Perhaps we should begin to expand the end-user documentation?
