### ISSUE TITLE
What are the available command line arguments?

### ISSUE THREAD

**Issue by PHPirates** [tectonic-typesetting/tectonic#373]
I couldn't find anything about it, and #62 suggests that it's not documented yet, just as the main website page.

The output of a compilation suggests that `--keep-intermediates` is one. 
I am especially interested in support for dvi output, synctex (#56, that's not a command line option?), and `-shell-escape` (but I see #38 is still open) but a more complete list would be kind of nice. In fact, any documentation would be kind of nice ;) 

I am willing to contribute a bit to the documentation, but I have no clue at all where to look in the source code.

**Comment by pkgw** [comment]
Yeah ... it's frankly embarrassing for me :-( I appreciate your persistence in working with the project despite its shortcomings!

Contributions are, of course, more than welcome (in the not passive-aggressive sense!). The arguments to the command-line client are defined [here](https://github.com/tectonic-typesetting/tectonic/blob/master/src/bin/tectonic.rs#L158).

Still to be determined: a framework for writing and publishing non-API docs. I get dissatisfied by GitHub Pages in a lot of ways, but a basic setup would be much better than the "nothing" that we currently have to offer.

**Comment by PHPirates** [comment]
No worries, I think Tectonic is useful as it is, and shortcomings are there to be fixed :) 

Thanks a lot for that link, apparently Tectonic has more features than I thought!

Yeah I found that once some template is in place for the documentation, it becomes much easier to work on it. It doesn't have to be perfect from the start. The only other thing I can suggest is the GitHub Wiki, because you can use Markdown on there. I don't know if it's a good idea to make it publicly editable, no experience with that. I recently started a wiki documentation using Asciidoc, and so far I found it works fine for me, I'm editing it locally.

**Comment by bjornbm** [comment]
Regarding the command line arguments specifically I find that the `--help` documentation is quite good:

```
$ tectonic --help
Tectonic 0.1.11
Process a (La)TeX document

USAGE:
    tectonic [FLAGS] [OPTIONS] <INPUT>

FLAGS:
    -h, --help                  Prints help information
    -k, --keep-intermediates    Keep the intermediate files generated during processing
        --keep-logs             Keep the log files generated during processing
    -C, --only-cached           Use only resource files cached locally
    -p, --print                 Print the engine's chatter during processing
        --synctex               Generate SyncTeX data
    -V, --version               Prints version information

OPTIONS:
    -b, --bundle <PATH>            Use this Zip-format bundle file to find resource files instead of the default
    -c, --chatter <LEVEL>          How much chatter to print when running [default: default]  [possible values: default,
                                   minimal]
        --format <PATH>            The name of the "format" file used to initialize the TeX engine [default: latex]
        --hide <PATH>...           Tell the engine that no file at <PATH> exists, if it tries to read it
        --makefile-rules <PATH>    Write Makefile-format rules expressing the dependencies of this run to <PATH>
    -o, --outdir <OUTDIR>          The directory in which to place output files [default: the directory containing
                                   INPUT]
        --outfmt <FORMAT>          The kind of output to generate [default: pdf]  [possible values: pdf, html, xdv, aux,
                                   format]
        --pass <PASS>              Which engines to run [default: default]  [possible values: default, tex,
                                   bibtex_first]
    -r, --reruns <COUNT>           Rerun the TeX engine exactly this many times after the first
    -w, --web-bundle <URL>         Use this URL find resource files instead of the default

ARGS:
    <INPUT>    The file to process, or "-" to process the standard input stream
```

Of course, it requires installing `tectonic` first which may be an obstacle to some.

I second the comment from @PHPirates that you are more likely to get doc contributions if there is a framework in place. FWI one of my repos has a publicly editable Github wiki and haven't had any problem with spammers (a Github user is still required to edit).
