### ISSUE TITLE
Whitespace difference from pdflatex

### ISSUE THREAD

**Issue by bjornbm** [tectonic-typesetting/tectonic#376]
When built with `tectonic` the following document gets less whitespace between the section number and text compared to `pdflatex`. If you cannot reproduce it might be particular to my pdflatex installation. If you can reproduce it, is it intentional or a bug?

Here is the document:

```
\documentclass{article}
\usepackage[a5paper]{geometry}
\begin{document}

\section{Hello}

Some text.

\end{document}
```

(The papersize is there to make both tools produce the same output size, see #126).

Here is a “visual diff” of the outputs from both tools highlighting the difference:

![diff76901](https://user-images.githubusercontent.com/37268/57216182-6ee6d800-6fef-11e9-985e-f8232fc7d258.png)

**Comment by bjornbm** [comment]
Turns out the `xetex` output is identical to `tectonic`, so `pdflatex` is the odd one out. I guess this is expected behavior so sorry for the noise!

**Comment by spl** [comment]
@bjornbm Yes, at this point, I think most of the rendering behavior of `xelatex` will be the same with `tectonic`.

**Comment by bjornbm** [comment]
Thanks @spl! It's nice to see a name I recognize from the Haskell community; it increases my confidence in tectonic. :)

I do actually have another case where I am not getting the same amount of whitespace between `xelatex` and `tectonic`. Will try to narrow it down to a minimal case and open a new issue later.

**Comment by spl** [comment]
@bjornbm I knew your name looked familiar... 😉 

But don't take me as a reason for trusting Tectonic. I think @pkgw has done a pretty good job of it. I'm just an occasional/aspiring contributor.

**Comment by pkgw** [comment]
Thanks @spl, but I'll make a point of mentioning that we need all the occasional/aspiring contributors we can get! — I started a new job that's really cratered my ability to spend time on Tectonic and I'd love to see the project grow.
