### ISSUE TITLE
dyld: Library not loaded: @rpath/libintl.8.dylib

### ISSUE THREAD

**Issue by Okhan97** [tectonic-typesetting/tectonic#384]
Hi, 

This error appears when I try to run my c code:
`dyld: Library not loaded: @rpath/libintl.8.dylib`
` Referenced from: /Users/okhan/Desktop/U/EDD/T2-2019-1-Okhan97/./beholder`
` Reason: image not found`

There was an old [issue](https://github.com/tectonic-typesetting/tectonic/issues/40) with the same problem, but after trying `conda update --all` and `conda install -c conda-forge gettext=0.19.7` the problem persisted.

![image](https://user-images.githubusercontent.com/26289334/58032939-8e9ef580-7af1-11e9-9f96-3df140b5cd13.png)
 This is my OS

**Comment by spl** [comment]
Can you walk us through the steps you went through to get to this point?

**Comment by Okhan97** [comment]
I can't remember all of what I did, but just a few things.
I was trying to install gtk on my mac but the library has a lot of problem with macos, so I was following a lot of instructions over the internet, I think the last one I did was changing PKG_CONFIG_PATH because of a previous error ([issue](https://github.com/lovell/sharp/issues/1603)).

Im sorry for not remember anything, I had a homework to do so finally I gave up and made an ubuntu partition (if you need anymore information just tell what commands to run).

PD: I also notice that when I run the `make` it doesn't print the compiled files, it only says `done`. This itself doesn't raise an error but I find it odd, before this error it usually printed something like `compiled 'obj/beholder/main.o'` for all the compiled files

**Comment by spl** [comment]
Thanks. I apologize if I missed something, but it's not clear to me from your report that your problem is with [Tectonic](https://tectonic-typesetting.github.io/). Are you trying to build or install Tectonic?

**Comment by Okhan97** [comment]
Oh sorry I think I got confused, this is not the place for this issue.

**Comment by spl** [comment]
@Okhan97 No problem. Hope you get it sorted out!
