### ISSUE TITLE
Fails to inlcude pdf file as graphic

### ISSUE THREAD

**Issue by timokau** [tectonic-typesetting/tectonic#393]
When trying to include the file `uni-logo.pdf` in the `figures` directory of [this template](https://cs.uni-paderborn.de/fileadmin/informatik/fg/cn/Stuff/thesis.zip) (not sure if I have permission to re-host only the pdf, so I'm linking the zip), tectonic fails:

```
[timo@desk:~/data/documents/uni/ba/paper/thesis]$ tectonic -p minimal.tex 
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
(minimal.tex
LaTeX2e <2018-04-01> patch level 4
Babel <3.20> and hyphenation patterns for 84 language(s) loaded.
(article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(size10.clo)) (graphics.sty (trig.sty) (graphics.cfg) (xetex.def)) (minimal.aux
)
warning: No trailer.  Are you sure this is a PDF file?
warning: No trailer.  Are you sure this is a PDF file?
warning: buffer:
stream36 /L 113 /Filter /FlateDecode /Length 40 0 R >> eb5b04cb37c65124>]
H�b``g``����������@,
�

 b
  �@��38��E��ľ

              Lo�
                 �( ah$���~��
0�������H3�@�<-

warning: buffer:
stream36 /L 113 /Filter /FlateDecode /Length 40 0 R >> eb5b04cb37c65124>]
Hb``g``@,


b
 @38Eľ

      Lo
        ( ah$~
0H3@<-

warning: Error while parsing PDF file.
warning: Error while parsing PDF file.

! Unable to load picture or PDF file 'figures/uni-logo.pdf'.
<to be read again> 
                   }
l.4 \includegraphics{figures/uni-logo}
                                      
No pages of output.
Transcript written on minimal.log.
error: the TeX engine had an unrecoverable error
caused by: halted on potentially-recoverable error as specified
debugging: backtrace follows:
stack backtrace:
   0:     0x5599787d3c5d - <no info>
   1:     0x5599787d3082 - <no info>
   2:     0x5599787d2818 - <no info>
   3:     0x5599787d2b95 - <no info>
   4:     0x5599785f3f0c - <no info>
   5:     0x5599785dded5 - <no info>
   6:     0x5599785dab1c - <no info>
   7:     0x5599785dc076 - <no info>
   8:     0x5599785eaae2 - <no info>
   9:     0x5599785e3ef2 - <no info>
  10:     0x559978848e12 - <no info>
  11:     0x5599788587e9 - <no info>
  12:     0x55997885540f - <no info>
  13:     0x5599785eb844 - <no info>
  14:     0x7f94ded38b8d - <no info>
  15:     0x5599785d9019 - <no info>
  16:                0x0 - <no info>
```

Where `minimal.tex` is:

```tex
\documentclass{article}
\usepackage{graphics}
\begin{document}
\includegraphics{figures/uni-logo}
\end{document}
```

**Comment by spl** [comment]
What happens when you use `xelatex` instead of `tectonic`?

**Comment by timokau** [comment]
It produces a pdf without errors.

**Comment by timokau** [comment]
Also the `uni-logo.pdf` file can be viewed without issues in a pdf viewer (zathura).

**Comment by pkgw** [comment]
I think this is a bug in Tectonic's I/O layer!

When processing this PDF, at [dpx-pdfobj:3138], the PDF parsing code gets the current file offset by calling `ttstub_input_seek` and gets a result of 686. However, in the next line, it reads a line of text from the PDF stream and gets a buffer starting with `trailer` ... and the "t" is at offset 685, not 686. The confusion resulting from this inconsistency leads to the error.

The Tectonic I/O layer has a shim to provide `ungetc`-like functionality, which some parts of the C code want, so my guess is that this we've got a bug that results in the reported file offset and the file data getting out of sync.

This would be consistent with things working fine in xelatex.

[dpx-pdfobj:3138]: https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/dpx-pdfobj.c#L3138

**Comment by pkgw** [comment]
Yup, a patch to `InputHandle::try_seek` fixes things.

@timokau Would it be OK to include the logo PDF in our test suite? I'd like to create a regression test for this issue, but seeing as it's only just come to our attention, I suspect that it would be challenging to create a different PDF file that would trigger the same issue.

**Comment by timokau** [comment]
Great, thanks for looking into this!

> Would it be OK to include the logo PDF in our test suite

I'm not sure. Personally I don't care, and I don't really think anyone else would either. But I don't know about the legalities. The thesis template is under the copyleft [MPL2](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) license. There is a German text about the Logo on the university page, but it seems mostly focused in the usage of the Logo for marketing etc. It says 

> Achtung! Das Logo der Universität Paderborn darf nur im Auftrag und im Sinne der Universität verwendet werden. Die Benutzung muss durch eine offizielle übergeordnete Stelle der jeweiligen Fakultäten, Institute oder Bereiche autorisiert werden.

roughly translated:

> Attention! The university logo must only be used by order (not sure if that is the right translation) and in terms of the university. The usage must be authorized by the responsible faculties, institutes or sectors.

So probably nobody cares about usage in a test suite, but I don't know if its technically allowed.
