### ISSUE TITLE
dyld: Library not loaded: @rpath/libintl.8.dylib

### ISSUE THREAD

**Issue by babycamel** [tectonic-typesetting/tectonic#40]
Installed this with conda and get this error on the first test. Running this on a Mac.

I also get Referenced from: anaconda3/lib/libharfbuzz-icu.0.dylib
  Reason: image not found

As part of the error message. Perhaps I should build from scratch with Rust?

**Comment by pkgw** [comment]
Hmmm, the Anaconda approach should be resistant to these kinds of problems.

Do you have environment variables like `DYLD_LIBRARY_PATH` set? I believe that when they're set (there are many variant names that can have similar effects) the dylib loading can fail in ways resembling this.

**Comment by babycamel** [comment]
I don't think so but I will check, it may be a conflict with something else I have installed. Meantime if I separately install harfbuzz is that a possible workaround?

Thanks

**Comment by pkgw** [comment]
I think that with the way that the `conda` binaries have their dylib search paths set up, a separate harfbuzz install will not be helpful.

If you have developer tools installed on your system, I've updated the install instructions to describe [the cargo-based install method](https://tectonic-typesetting.github.io/en-US/install.html#the-cargo-install-method) which might give you better results.

**Comment by dfm** [comment]
P.S. Installing with cargo using your new instructions worked perfectly for me.

**Comment by pkgw** [comment]
Aha. It appears that the `conda-forge` version of the `gettext` package, which includes `libintl.dylib`, has fallen behind the one provided by Continuum.io. Conda-forge's version (0.19.7) provides the `.8` version of the library, but the Continuum.io (`defaults`) version (0.19.8) provides the `.9` version.

@babycamel or @dfm, if you do a `conda update --all` after configuring your installation to use the `conda-forge` "channel", does it prompt you about downgrading the `gettext` package? If so, I think that doing so will fix the problem.

**Comment by dfm** [comment]
Cool. I figured that it was probably something like that. I'm not going to try that command because I don't like the conda-forge numpy :-), but `conda install -c conda-forge gettext=0.19.7` seems to have done the trick for me.

**Comment by pkgw** [comment]
It looks like the version bump of the libintl dylib [was a mistake](https://lists.gnu.org/archive/html/info-gnu/2016-06/msg00006.html) so perhaps this will fix itself soon enough. I've filed [an issue with Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues/1995).

**Comment by pkgw** [comment]
@babycamel OK, if you are still facing this problem, a `conda update --all` should fix it for you. The Anaconda installation docs have been updated to hopefully prevent analogous problems in the future. Therefore I think this issue can be closed.

**Comment by Okhan97** [comment]
Did `conda update --all` and the problem persists :/

**Comment by pkgw** [comment]
@Okhan97 The problem discussed in this bug was a pretty old one associated with a packaging issue that should have gone away a while ago. If you're having a similar problem, can you please file a new bug with information about what operating system an installation method you're using? Thanks.
