### ISSUE TITLE
Document the location and structure of the cache directory

### ISSUE THREAD

**Issue by iandol** [tectonic-typesetting/tectonic#45]
Hi, as tectonic downloads all the required files, where are they stored? Are these also removed if we use `conda` to uninstall tectonic?

BTW, all my tex files compiled just fine on first try, congratulations!

**Comment by rekka** [comment]
Without `conda` (not sure if `conda` changes this):

Linux: `~/.cache/Tectonic`
macos: `~/Library/Caches/Tectonic`

It uses the [app_dirs](https://crates.io/crates/app_dirs) crate to determine these.

Just run 

```
find ~ -iname Tectonic
```

**Comment by iandol** [comment]
I installed with conda, and I also have a `~/Library/Caches/Tectonic` present. WTF this directory is only 20MB of stuff having downloaded all the packages and fonts I use!!!! This makes even BasicTeX seem bloated in comparison!!! Amazing. It would be good to document this somewhere, and uninstall steps for users...

**Comment by pkgw** [comment]
Yes, this should be added to the documentation somewhere. Too bad "the documentation" doesn't actually exist just yet ...

**Comment by pkgw** [comment]
Subsumed into #62.

**Comment by alexreg** [comment]
It would be nice if tectonic itself had a command-line option to spit out this path, but glad I found this. The Tectonic Book could definitely use some loving attention, but good to know it exists already in some form.
