### ISSUE TITLE
Tectonic outputs NSAutoreleasePool log message

### ISSUE THREAD

**Issue by iKevinY** [tectonic-typesetting/tectonic#47]
I get an `NSAutoreleasePool` log message when running Tectonic 0.1.5 on macOS 10.12.5. Doesn't seem to impede the PDF generation in any way, though.

```
$ tectonic resume.tex
note: this is a BETA release; report issues at https://github.com/tectonic-typesetting/tectonic/issues
Running TeX ...
warning: could not calculate MD5 of file "resume.out": it does not exist
note: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Rerunning TeX because "resume.aux" changed ...
2017-05-31 21:27:30.151 tectonic[4170:87768] *** -[NSAutoreleasePool release]: This pool has already been released, do not drain it (double release).
Running xdvipdfmx ...
Writing resume.pdf (25785 bytes)
Skipped writing 2 intermediate files (use --keep-intermediates to keep them)
```

**Comment by pkgw** [comment]
I'm not a Mac user. Anyone know what this means? Sounds like a double-free of a memory pool ... and it's got Mac-specific indicators that lead me to suspect that the problem is somewhere in either [XeTeXFontInst_Mac.cpp](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/XeTeXFontInst_Mac.cpp) or [XeTeXFontMgr_Mac.mm](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/XeTeXFontMgr_Mac.mm).

@khaledhosny any chance that you're familiar with this from XeTeX proprer?

**Comment by khaledhosny** [comment]
No idea off hand, looks like double free in some of the Mac specific parts. If it doesn't happen with XeTeX then something changed and is causing it.

**Comment by pkgw** [comment]
OK. @iKevinY are you able to provide a minimal test document that triggers the message? I can get my hands on a Mac and investigate.

**Comment by iKevinY** [comment]
It appears the `unicode-math` package causes the message; I reduced the document to the following:

```tex
\documentclass{article}
\usepackage{unicode-math}

\begin{document}
Foo
\end{document}
```

**Comment by rekka** [comment]
I am also getting rare NSAutoreleasePool messages on my Mac, even during the `trip_test` (running `cargo test`). It doesn't seem to be deterministic though, probably a race condition of sorts...

**Comment by efx** [comment]
I can reproduce the `NSAutoreleasePool` message given the following document:
```tex
\documentclass{article}
\begin{document}
Foo
\end{document}
```
I see it while running tectonic@0.1.11 which I installed on macOS using [nix](https://nixos.org/nix/):
```
~/f/e/tectonic $ tectonic tectonic-47.tex
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
Rerunning TeX because "tectonic-47.aux" changed ...
2019-08-05 16:11:51.669 tectonic[22250:1182951] *** -[NSAutoreleasePool release]: This pool has already been released, do not drain it (double release).
Running xdvipdfmx ...
Writing tectonic-47.pdf (2332 bytes)
Skipped writing 1 intermediate files (use --keep-intermediates to keep them)
``` 

I can test proposed patches as well. Given I only run tectonic on macOS for development previews I do not consider this a pressing issue.

**Comment by pkgw** [comment]
@efx Yeah, seeing as this issue has sat around for a few years at this point, it seems pretty clear that it's not a showstopper. Would still definitely like to make it go away at some point though! If nothing else, #101 is one of our older pull requests and I'd love to close it out with a real resolution.

**Comment by rekka** [comment]
It seems to have been fixed on the `master` branch; see https://github.com/tectonic-typesetting/tectonic/pull/101#issuecomment-520293455.

**Comment by iKevinY** [comment]
Awesome, thanks for verifying the fix @rekka; looks like we can close this now!
