### ISSUE TITLE
build.rs and cross-compilation

### ISSUE THREAD

**Issue by ratmice** [tectonic-typesetting/tectonic#476]
While (trying to) test #473 I ran across the issue that when cross compiling,
build.rs `#[cfg(target_os = "...", target_arch = "...")]` is compiling with `target=host`, 
because build.rs runs on the host, these should probably be migrated to using.

`CARGO_CFG_TARGET_OS`, and `CARGO_CFG_TARGET_ARCH`,

##### pkg_config:
I'm not sure what if anything, `pkg-config` requires from build.rs to work properly.
I didn't see anything that would allow us to send it the target so I imagine it punts to the user.

**Comment by pkgw** [comment]
I am a bit surprised that the `cfg` bits are misleading in this way, but that indeed seems to be how things work. The [target_build_utils](https://docs.rs/target_build_utils/0.3.1/target_build_utils/) crate might be helpful?

For pkg-config, I think the necessary setup has to happen outside of build.rs. For the MUSL cross-compile, and in other cases, there's a `PKG_CONFIG_ALLOW_CROSS` environment variable that we have to set .. some grepping for that might yield helpful examples from our CI setup.

**Comment by ratmice** [comment]
I don't think the `target_build_utils` crate will be helpful, it is deprecated and recommends using the 
it says:

> DEPRECATED: Use environment variables set by cargo from 1.14.0 onwards.
> They look like this: CARGO_CFG_TARGET_OS, CARGO_CFG_TARGET_ENV…

According to the Commits dropdown in #449 we have dependencies that require v.1.34.0, so
we can just use the CARGO_CFG_TARGET_* i think.

I did some looking into how to write proc_macros that emulate `cfg!(...)` It seems like that may be possible under v.1.30+, I haven't managed to think of any other API which is going to be nearly as nice, anyhow i will play around with various options and scour crates.io to see if we missed anything more recent.

Thanks for the tip to the CI setup, i'll have a look.

**Comment by pkgw** [comment]
Ah, good reading comprehension :+1:

Given that proc-macros make life hard for static builds, I would like to avoid using them for the `build.rs` script. I agree that it will probably be much less nice, but on the other hand, `build.rs` is just a bit of infrastructure, not the main API.

**Comment by ratmice** [comment]
Thanks, i'll have a look with that in mind.

**Comment by pkgw** [comment]
Fixed in #477!
