### ISSUE TITLE
Add installation instructions for Windows

### ISSUE THREAD

**Issue by vks** [tectonic-typesetting/tectonic#483]
Currently, installation on Windows is completely undocumented. It is necessary to study the Appveyor scripts:
```yaml
  - if "%target_env%" == "msvc" %USERPROFILE%\vcpkg\vcpkg install --triplet x64-windows-static fontconfig freetype harfbuzz[icu,graphite2]
  - if "%target_env%" == "msvc" set VCPKG_ROOT=%USERPROFILE%\vcpkg
  - if "%target_env%" == "msvc" set TECTONIC_DEP_BACKEND=vcpkg
  - if "%target_env%" == "msvc" set RUSTFLAGS=-Ctarget-feature=+crt-static
```
In particular, I think the following should be documented:
* How the `TECTONIC_DEP_BACKEND` environment variable works.
* On Windows, `vcpkg` should be used to install `fontconfig freetype harfbuzz[icu,graphite2]`.
* The environment variable `VCPKG_ROOT` has to be set.
* `RUSTFLAGS=-Ctarget-feature=+crt-static` has to be set.

**Comment by pkgw** [comment]
This is completely correct. The [basic Tectonic installation instructions] do not offer a lot for Windows users.

[basic Tectonic installation instructions]: https://tectonic-typesetting.github.io/en-US/install.html

One related issue is that it would be very nice if we could provide pre-built binaries for Windows users — it is probably true that there are a lot more people on Windows who just want to install the executable, than ones who want to compile the project themselves. This is not an area that I'm very familiar with, and suggestions from Windows folks would be *very* welcome.

**Comment by ComFreek** [comment]
Is this issues still up-to-date? Apparently, [the latest prerelease](https://github.com/tectonic-typesetting/tectonic/releases) is providing a Windows binary. A [Chocolatey package](https://chocolatey.org) would also be nice. That's something I've got some experience with in creating and maintainig, so I could do this if you want me to.

**Comment by pkgw** [comment]
@ComFreek Our Windows installation instructions are still not very good, but it is true that I set up the CI/CD to start providing Windows binaries. I only know a little about Chocolatey — if you could help set up a package, that would be great! If needed we can make a new release to get an official Windows standalone binary out there.

**Comment by whjochim** [comment]
I've created documentation for building under windows.

https://github.com/tectonic-typesetting/tectonic-typesetting.github.io/pull/23

I also agree that a chocolatey package and github release of a static binary would be really nice

**Comment by pkgw** [comment]
Between the previous contributions and some rearrangement I've done of the documentation, culminating in some doc changes in #782, I'm going to say that this issue has been fixed.
