### ISSUE TITLE
NSAutoreleasePool message is not fixed in macOS Catalina

### ISSUE THREAD

**Issue by ericnchen** [tectonic-typesetting/tectonic#496]
Hello,

I have the following installation:

* macOS 10.15.1 Catalina
* Tectonic 0.1.11 (via MacPorts)

When I run `tectonic`, I get the following output:

```
$ tectonic test.tex
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
Rerunning TeX because "test.aux" changed ...
2019-11-08 09:54:21.406 tectonic[1357:32811] *** -[NSAutoreleasePool release]: This pool has already been released, do not drain it (double release).
Running xdvipdfmx ...
Writing test.pdf (2616 bytes)
Skipped writing 1 intermediate files (use --keep-intermediates to keep them)
```

I am able this reproduce it with this simple document:

```
\documentclass{article}
\begin{document}
Test
\end{document}
```

There are existing issues (#47 and #101) about this message which were closed on 12 August 2019. According to https://github.com/tectonic-typesetting/tectonic/pull/101#issuecomment-520293455, @rekka says that the issue was fixed with 0e78c9564be430ec836c6168548540173d833b6a but the issue doesn't appear to be resolved. This is my first time using Tectonic and I've only used it with macOS Catalina, so I don't know if this issue is back because of Catalina or not.

Running `tectonic -c minimal` doesn't hide the message either:

```
$ tectonic -c minimal test.tex
2019-11-08 10:06:22.123 tectonic[1440:40848] *** -[NSAutoreleasePool release]: This pool has already been released, do not drain it (double release).
```

This isn't a big problem because the pdfs it generates are still fine. It's just an annoying message to keep seeing though.

**Comment by rekka** [comment]
Hi, thank you for the report. Unfortunately, the patch is not present in 0.1.11 yet (it's a version from Nov 2018). On the other hand, this problem appears to be completely harmless.

It should be included in the upcoming 0.1.12 release.

If you can, you might consider installing the current version on master. It also contains other improvements like better caching to avoid unnecessary network requests.

**Comment by pkgw** [comment]
Thanks @rekka. We are overdue for a release! I will see if I can cut one this week.

**Comment by efx** [comment]
@ericnchen thanks for reporting! [0.1.12](https://github.com/tectonic-typesetting/tectonic/tree/v0.1.12) has been released and I see [macports](https://ports.macports.org/ports/category/tex/) has it.

Could you try your steps again and see if those errors disappear? Thanks!

**Comment by mnrvwl** [comment]
ping @ericnchen

**Comment by pkgw** [comment]
Based on the lack of follow-up reports in the intervening years (!) since this arose, I'm going to go ahead and close this issue. If @ericnchen or anyone else sees it with a recent version, please comment here or file a new issue.
