### ISSUE TITLE
Build documentation for *docs.rs* website

### ISSUE THREAD

**Issue by alexreg** [tectonic-typesetting/tectonic#5]
Let's make sure Travis does this automatically too.

**Comment by musoke** [comment]
Is this to check that the docs can build? As far as I know, [docs.rs automattically  builds the documentation when updates are pushed to crates.io](https://docs.rs/about).

However, docs.rs does seem to have [failed to build the docs so far](https://docs.rs/crate/tectonic/0.1.3/builds). All using `rustc 1.17.0-nightly (0f34b532a 2017-02-21)`

**Comment by pkgw** [comment]
Yes, I think the docs will not build on docs.rs because of Tectonic's dependencies on various native C libraries. I am not sure of the best way to deal with this. But this connects to the larger challenge of making Tectonic build more comfortably within the Cargo/Rust ecosystem (cf #15).

**Comment by alexreg** [comment]
Ah yes, you're right about that @musoke. Maybe docs.rs can somehow be told to ignore the native dependencies though, when generating docs? I can have a look into this at some point, perhaps.

**Comment by musoke** [comment]
Didn't dig too deep, but here are some relevant links: 
* https://github.com/onur/docs.rs/pull/73 (would fix this issue?)
* https://github.com/onur/docs.rs/issues/93

**Comment by alexreg** [comment]
Yes, I believe 73 would fix the issue, and be the more elegant solution.

**Comment by pkgw** [comment]
I've just published version 0.1.6 of the crate, and confirm that we're now available on docs.rs!
