### ISSUE TITLE
Memory isn't de-allocated between TeX runs

### ISSUE THREAD

**Issue by YaLTeR** [tectonic-typesetting/tectonic#512]
When tectonic runs TeX multiple times the memory usage continues to grow and doesn't drop between TeX runs. I'm compiling this large beamer presentation and I can only manage it once every 5 attempts because tectonic keeps running out of memory on the third run and getting OoM-killed, even though the increase after every individual TeX run isn't that large.

**Comment by pkgw** [comment]
Would you be able to share the file(s) used to create the presentation, privately if you would prefer? We know that we have some memory leaks from one run to the next (since the original code assumes that the program will just exit and release all memory) and your files sound like a great test case for chasing them down!

**Comment by YaLTeR** [comment]
I can share them privately, yeah. Where should I send the archive?

**Comment by pkgw** [comment]
If the files aren't too large (say <20 MB), you can email them directly to me at `peter@newton.cx`, otherwise can you please share them to that email address using a service like Google Drive, DropBox, etc.?

**Comment by YaLTeR** [comment]
I have shared the archive containing everything needed to build the presentation via Google Drive.

**Comment by pkgw** [comment]
@YaLTeR Message received — I'll take a look. Thanks!

**Comment by YaLTeR** [comment]
I updated to 0.1.12 and this might be mostly fixed, actually. The memory still doesn't drop but it's a fraction of what it used to be, and it seems to not grow at all for the subsequent TeX runs.

**Comment by pkgw** [comment]
Excellent! I am going to close this issue but will see if I can take a look at your files and file issues for any memory leaks they reveal. Feel free to reopen this if you see any more issues, particularly if you still occasionally see Tectonic getting OOM-killed.
