### ISSUE TITLE
Filenames in output should be quoted

### ISSUE THREAD

**Issue by alexreg** [tectonic-typesetting/tectonic#539]
This is motivated by the fact I get output like the following in the `LaTeX Compiler` log window in VSCode:

```
Writing /Users/alex/Documents/A filename with spaces.tex (123 bytes)
```

and only `/Users/alex/Documents/A` gets highlighted as a filename. In any case, the general practice is to enclose filenames in console output as `` `/a/b/c` ``, I believe. This would solve the issue.

I don't know if it covers all cases, but the `note_highlighted` fn (second parameter) seems to be responsible for this sort of printing. The enclosing of filenames in backticks is probably best done at call-site however (using a helper function?).

While I'm writing this, a bonus would be comma-separating the number of bytes, e.g., `123,456,789 bytes` -- or better yet, `123 MB` (also `kB` and `B` of course). All for readability of course, since this is nitpicking!

**Comment by pkgw** [comment]
There is almost surely a small Rust crate out there that implements the algorithm of taking a number of bytes and textifying it as `123 MiB` or whatever else as needed. Both of these suggestions are good and would make great pull requests for someone interested in making their first project contribution!

**Comment by alexreg** [comment]
@pkgw I'm really busy at the moment, but if someone doesn't get around to this in the next 2-3 weeks I should be able to do this! (Feel free to ping me around then.)

**Comment by ralismark** [comment]
Can this be closed? Looks like a fix has been merged.

**Comment by pkgw** [comment]
Sure! We can always reopen, or make a new issue, if there's more to do.

**Comment by alexreg** [comment]
Thanks, glad to see this has been fixed!
