### ISSUE TITLE
0.1.12 regression: \year displays unix epoch (1969) instead of current year

### ISSUE THREAD

**Issue by efx** [tectonic-typesetting/tectonic#540]
Props to my colleague @jjpilat for finding this.

When generating the following document using `tectonic -C`, v0.1.12 prints 1969 while v0.1.11 prints 2020:
```tex
\documentclass{article}
\begin{document}

\huge\bf{®\the\year}

\end{document}
```
I would expect the same output with either version.
Anyone know where I can start looking for what changed? I imagine this is one of the embedded dependencies, not necessarily the Rust portions of the codebase.

**Comment by NieDzejkob** [comment]
>  Anyone know where I can start looking for what changed? I imagine this is one of the embedded dependencies, not necessarily the Rust portions of the codebase.

Find the commit that broke it with `git bisect`.

**Comment by pkgw** [comment]
Sorry for taking a very long time to get to this! But, I am having trouble reproducing. If I run on `master` I get 2020 for the year as expected. I can't think of any changes that would be relevant that came in since the 0.1.12 release. What platform is this happening on? Is the use of the `-C` flag required to trigger the issue?

0.1.12 included PR #486 which is probably relevant, if we can narrow down a reproduction case

**Comment by efx** [comment]
@pkgw no apology needed! Good point about the `-C` flag.

I am wrong here. The issue is with how I am building and running tectonic versions. I use `nix-shell` on my macOS machine to create a development environment to compile tectonic. nix-shell resets a number of things to maintain environment purity. I wager it resets locale settings or it alters the underlying environment so that year is computed as the UNIX epoch.
I can reproduce it with:
1. ` nix-shell ~/.nix-defexpr/channels/nixpkgs-latest/ -A tectonic`
    - `nixpkgs-latest` is a channel I've added pointing at https://github.com/NixOS/nixpkgs/tree/master
2. `cargo build --release`
3. `./target/debug/tectonic simple.tex`

Alongside that, I verified `0.1.12-dev` installed on a GNU/Linux correctly prints 2020 for the year.
Given the extraordinary edginess of this case, I will close.

**Comment by pkgw** [comment]
Bizarre! I'd love to dive into this to figure out what's going on exactly, but agreed that this is an extreme edge case and there are probably better ways for folks to spend their time ...
