### ISSUE TITLE
Github Action For Tectonic

### ISSUE THREAD

**Issue by vinay0410** [tectonic-typesetting/tectonic#548]
Hi, I have created a Github Action to Compile tex files easily using Tectonic.
Link: [https://github.com/marketplace/actions/compile-latex](https://github.com/marketplace/actions/compile-latex)

I was hoping if it could be added to the `README.md` or Tectonic's website. This would help users who already have their `.tex` files on Github to easily compile them, without having to install Tectonic locally.

**Comment by vinay0410** [comment]
Should I open a PR for this ?

**Comment by pkgw** [comment]
Hi, sorry for not responding sooner ­— this is awesome! If you'd like to open a PR, you are more than welcome to do so, but I can add it to the README and website if it would be inconvenient.

**Comment by vinay0410** [comment]
Hi @pkgw , It would be very helpful, if you could add it to the README and website

**Comment by pkgw** [comment]
Added to README too. Thanks @vinay0410 and @Jassob!
