### ISSUE TITLE
Undefined control sequence errors associated with polyglossia/listings packages (path search failure?)

### ISSUE THREAD

**Issue by impugachev** [tectonic-typesetting/tectonic#553]
I tried to compile a document using listings package and got an error. (https://github.com/impugachev/diploma/pull/1/checks?check_run_id=453956614)
But latexmk was able to compile the document without problems.(https://github.com/impugachev/diploma/pull/2/checks?check_run_id=453966977)

**Comment by pkgw** [comment]
Yikes, this error seems to involve the interaction of many packages. This is the shortest example I can find that triggers the same error message:

```tex
\documentclass{report}

\usepackage{listings}
\lstdefinelanguage{json}{
  numbers=left
}

\usepackage{polyglossia}
\setdefaultlanguage[spelling=modern]{russian}

\usepackage{fontspec}
\defaultfontfeatures{Mapping=tex-text}
\setmainfont{cmunrm.otf}[%
  Ligatures = TeX,
  BoldFont = cmunrb.otf,
  ItalicFont = cmunti.otf,
  BoldItalicFont = cmunbi.otf,
]%

\begin{document}
\lstinputlisting[language=json]{example.json}
\end{document}
```

(with some example.json file) It looks like latexmk is using xelatex and succeeding.

For what it's worth, Tectonic doesn't execute external programs and so it doesn't work with biber/pdflatex, so that would prevent it from working with this document right now. But the error that you're getting appears to be a separate issue that marks a divergence between XeLaTeX and Tectonic, which we shouldn't have.

**Comment by jpgoldberg** [comment]
I appear to be having a similar problem. Among the packages I use are `fontspec`, `listings`, and `polyglossia`. xelatex works on the project, but tectonic starts throwing errors when processing polyglossia. It also complains about not loading any hyphenation patters.

 (My document is enormously complex, and I haven't attempted to create a minimum non-working example.)

**Comment by elliott-wen** [comment]
I used tectonic in SwiftLaTeX, a webassembly-based client-side latex
editor.

I reckon it may be a path search problem. Texlive uses the kpathsea library
to handle path searching. Kpathsea has quite complex and subtle logics in
order to fetch correct files.
If I understand correctly, Tectonic uses a relatively simple filename
matching mechanism, which might trigger unnoticed bugs in some margin
cases. In my system, I used a relatively dumb method, which forwards
kpathsea search requests to a remote server, this saves me a lot of
headache.




Jeffrey Goldberg <notifications@github.com> 于2020年6月28日周日 下午5:19写道：

**Comment by jpgoldberg** [comment]
It seems likely that @elliott-wen is correct and that tectonic isn't finding or fetching the language specific files that polyglossia tries to load. In searching (and failing) for a solution or work-around, I found a discussion forum thread from a year ago that also raised the question.

https://tectonic.newton.cx/t/missing-hyphenation-patterns-for-my-language-where-can-i-add-them/

**Comment by jpgoldberg** [comment]
It might be something else. Here is the relevant part of my log

```
Package polyglossia Warning: File gloss-*.ldf does not exist!
(polyglossia)                I will nevertheless try to use hyphenation pattern
s for *. on input line 31.


Package polyglossia Warning: \setlocalhyphenmin useless for unknown language * 
on input line 31.


Package polyglossia Warning: No hyphenation patterns were loaded for `'
(polyglossia)                I will use \language=\l@nohyphenation instead on i
nput line 31.

\l@* = a dialect from \language\l@nohyphenation 
```

So for some reason polyglossia has come to believe that the language name is "`*`" with the corresponding language definition file `gloss-*.ldf`. Instead we should be looking for either `gloss-english.ldf` or `gloss-russian.ldf` (in my case).

Looking through polyglossia.sty I don't really see how this is happening, but it uses some `etools.sty` idioms for defining control strings that I'm not familiar with. So I don't see where `*` could be accidentally passed as an argument.

**Comment by elliott-wen** [comment]
Could you kindly give me a minimal snippet to reproduce the bug?

Cheers


Jeffrey Goldberg <notifications@github.com> 于2020年6月29日周一 上午9:09写道：

**Comment by jpgoldberg** [comment]
It appears that when I use tectonic on my document, but `.aux` file ends up with lots of things like

```
\selectlanguage *[variant=canadian]{english}
\@writefile{toc}{\defcounter {refsection}{0}\relax }\@writefile{toc}{\selectlanguage *[variant=canadian]{english}}
\@writefile{lof}{\defcounter {refsection}{0}\relax }\@writefile{lof}{\selectlanguage *[variant=canadian]{english}}
\@writefile{lot}{\defcounter {refsection}{0}\relax }\@writefile{lot}{\selectlanguage *[variant=canadian]{English}}
```

But the `\selectlanguage` macro doesn't have a *-ed form when polyglossia is loaded. So we are seeing "*" as the name for the language in all of these things in the `.aux`. I don't know what is writing those out.

**Comment by jpgoldberg** [comment]
> Could you kindly give me a minimal snippet to reproduce the bug?

@elliott-wen, my project is massive, with a huge number of weirdly interacting parts. I will see if I can create a minimal example, but I can't promise to. I also have (at least) [one other problem](https://github.com/tectonic-typesetting/tectonic-staging/issues/14) with getting it to work with tectonic.

It may be that they are interrelated. I should point out that above where I looked at the biblatex source, I was looking at version 3.14 instead of version 3.11, which tectonic loads.

**Comment by pkgw** [comment]
Thanks for all of your patience and work to investigate this! I will see if I can start assisting.

@jpgoldberg If you are willing and able to convey to me a copy of the massive form of your project, that could still be helpful for debugging.

**Comment by pkgw** [comment]
I am working on an update to TeXLive 2020 and it may solve this issue! My reproduction case above no longer errors out, at least.

**Comment by pkgw** [comment]
The recent version 0.3 release of Tectonic updates the engine to TeXLive 2020, and tracking issue #669 shows how to beta-test the updated TeXLive 2020 support file bundle that goes with it.

**Comment by pkgw** [comment]
The new TeXLive 2020.0r0 bundle has been deployed, and I think it should fix this issue if you use it with one of the latest releases of the software. Please reopen or re-file if that turns out not to be the case!
