### ISSUE TITLE
Alternative License Text For Tectonic CFG Support

### ISSUE THREAD

**Issue by zicklag** [tectonic-typesetting/tectonic#565]
Hey there! I have just recently published the [`cfg_aliases`](https://docs.rs/cfg_aliases) crate which borrows a lot of code from the `tectonic_cfg_support::target_cfg!` macro and to comply with the license requirements I added the exact license text of tectonic to my crate's [NOTICES.md](https://github.com/katharostech/cfg_aliases/blob/master/NOTICES.md) file.

The license for Tectonic, though, contains the following statement: "Elements of the system from which it is derived are licensed under an extremely wide variety of open-source licenses."

This is completely untrue of the code that I actually included from Tectonic and seems to indicate that the license for use of my crate could be restricted by the terms of those "extremely wide variety of open-source licenses".

Would it be possible maybe to get a separate license file for the `tectonic_cfg_support` crate that I could include in my notices that wouldn't include that line?

This isn't a show-stopper or anything, but more like a bit of healthy legal paranoia. If it isn't possible to get a separate license text for one reason or another, I'm not actually too worried about it because I only use the code in `build.rs` scripts and it therefore can't effect the license of my delivered product, but I would still like to get it cleared up if possible.

**Comment by ratmice** [comment]
I think there is another pedantic legal reason to include a license in this subcrate, in that it has it's own crates.io release.  The copyright notice states that distributing it should have this notice intact, and so it is good to include that in the crates.io package as well.

**Comment by pkgw** [comment]
Fixed in #566. I will make a new release on crates.io momentarily. Thanks for reporting!

**Comment by zicklag** [comment]
Awesome. Thank you!
