### ISSUE TITLE
Some kind of community discussion forum

### ISSUE THREAD

**Issue by pkgw** [tectonic-typesetting/tectonic#57]
Tectonic is still very young, but there's been enough interest that I think it might be valuable to set up some kind of community discussion forum. I would lean towards a self-hosted instance of [Discourse](http://www.discourse.org/) which I think I can get up and running in a few hours.

Mailing lists / Google Groups are OK, but I think Discourse would be better, and the extra setup/maintenance overhead is probably not so big as to make it not worthwhile to go for it.

So that's my current plan. Comments welcome.

**Comment by katrinleinweber** [comment]
Discourse is a good choice in my experience :-)   But I am wondering: What are the arguments against simply continuing with this GitHub issue tracker?

**Comment by pkgw** [comment]
The issue tracker is fine for some code-development type discussions, but I think something like Discourse would be a better choice for user support, discussing potential new features, and so on.

I've had to work through a lot of technical problems, but hopefully I'm just about to finish up creating a Discourse instance on my personal web server!

**Comment by pkgw** [comment]
Done: https://tectonic.newton.cx/ .

**Comment by jtojnar** [comment]
Separate community fora are great for keeping the issue tracker focused on development, they are not without a flaw, though. Now developers’ and users’ attention is split between multiple platforms. I feel like the overhead does not outweigh the benefits for a relatively-low-activity projects like Tectonic. Something low threshold like IRC might be alright, though.

For help, users could be redirected to StackExchange, where many of them already are registered.

**Comment by katrinleinweber** [comment]
The issue tracker itself doesn't really need to be focussed on development / for developers. Its tags have to be. Namely: applied correctly, focussing, splitting and switching attention is possible within the same environment ;-)
