### ISSUE TITLE
Segmentation fault on repeated failure under async executor

### ISSUE THREAD

**Issue by fmgoncalves** [tectonic-typesetting/tectonic#574]
I am using tectonic as a library for generating pdfs on an [actix-web server](https://actix.rs/).

This only seems to happen when running on different threads under an async executor. The way to trigger a segfault is to repeat an api call that causes a failed latex compilation:

After a first call to `latex_to_pdf` (for example, calling with invalid latex), on a second invalid call [XeTeXFontMgr_FC::initialize](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/xetex-XeTeXFontMgr_FC.cpp#L310) does not get called, and therefore when it tries to terminate [FcFontSetDestroy](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/xetex-XeTeXFontMgr_FC.cpp#L338) is called with NULL, segfaulting.
[Here is the full stack trace](https://github.com/tectonic-typesetting/tectonic/files/4504028/segfault.txt)

Placing a guard on the call

```cpp
    if (allFonts != NULL) {
        FcFontSetDestroy(allFonts);
        allFonts = NULL;
    }
```
appears to prevent this, but I am not familiar with this codebase so I can't tell if it is just a patch on the symptoms rather than a fix for the root cause.

**Comment by pkgw** [comment]
Thanks for the report! The lifecycle management inside the C code is a bit of a mess because it was never meant to be rerun in the way that Tectonic enables. The hope is to gradually clean it all up, but it will take a while. In the meantime, I think it would definitely be good to add your guard. Would you like to create a PR, or shall I do it for you?

**Comment by fmgoncalves** [comment]
PR created (#579).

Thanks for tectonic, this project feels to be extremely promising and is an absolute pleasure to work with!

**Comment by pkgw** [comment]
Thanks! PR merged.
