### ISSUE TITLE
Bad user experience if cached web-bundle was missing a file

### ISSUE THREAD

**Issue by pkgw** [tectonic-typesetting/tectonic#6]
Say that the user tried to compile a document, and the compilation failed because some needed resource file was missing from the web bundle. The web bundle is then updated with a new version that adds the needed file.

If the user re-compiles the document, though, they won't get the fixed file: the bundle manifest will log that the file is missing, so Tectonic won't re-check the bundle SHA256 and realize that it's changed. That's too bad.

The best fix might be to add an option or subcommand to force Tectonic to re-check the SHA256 of the bundle. Some of the relevant error messages could suggest this course of action, although ideally we'll have really thorough bundles such that missing files are a rare occurrence.

**Comment by rekka** [comment]
I believe this issue will be resolved by #431 since there is no need to record missing files in the manifest.

**Comment by jessestricker** [comment]
Hi, I think this issue just happened to me (correct me if I'm wrong):

I'm a first-time user and tried `tectonic -X compile thesis.tex` on my current project root file and it failed reporting some files missing regarding `biblatex`.
I figured I did something wrong and created a new workspace using `tectonic -X new some-dir` and tried building in there with `tectonic -X build` and it failed again (with some files missing).

Eventually I figured to delete the user cache dir and after that building in the workspace worked just fine.
So either #431 didn't fix this, or my case is a different issue.

**Comment by pkgw** [comment]
@jessestricker Your issue is something different, since this one has to do with changes to the web-based bundle data files. If you can find a way to reproduce the issue you experienced, please file a new issue for it. Thanks!

As it happens, since the original issue has been idle for a long time, I'm going to close it.
