### ISSUE TITLE
Explain ilk, please

### ISSUE THREAD

**Issue by gtors** [tectonic-typesetting/tectonic#607]
I'm trying to figure out what is going on in `bibtex.c` (the code ~~is total mess~~ is bit creepy). But can't understand the abbreviation `ilk` (`str_ilk`). What is it?

**Comment by elliott-wen** [comment]
I defend author in this matter. Bibtex was originally written in old old
Pascal (more specifically Web), where variable names have lots of naming
limitations. to compile bibtex using modern compilers, a Pascal to c
translator (CWeb) has to be used.
The translator ensures functional correctness but not source code
readability.

The bibtex.c you are seeing is actually a much readable version than the
original translatation. author also put lots of effort changing global
variable declarations to static to ensure no  naming pollution to other c
files. This is a painstaking process. Author has my respect.

If you want to understand what's going on in bibtex. I would suggest you
read the origin Pascal version (bibtex.web), where detailed comments can be
found.

**Comment by gtors** [comment]
Thank you for your quick response and detailed explanation!

**Comment by elliott-wen** [comment]
This link may be helpful

https://github.com/TeX-Live/texlive-source/blob/trunk/texk/web2c/bibtex.web

>

**Comment by pkgw** [comment]
Hah, no offense taken, as indeed this is not code that I have written from scratch :-)

For what it's worth, as best I can tell, the "ilk" is meant as [its English usage](https://www.dictionary.com/browse/ilk) — basically a synonym for "kind" or "type". It seems to record the different usages that different strings in bibtex have. This is a great example of the sort of TeX-y wordplay that I am not such a big fan of — it can be cute, but it makes the ecosystem confusing for newcomers. I would rather have very boring, un-creative code and terminology that is accessible to as many people as possible. The tool is still going to be powerful.
