### ISSUE TITLE
Looks like typo

### ISSUE THREAD

**Issue by burrbull** [tectonic-typesetting/tectonic#617]
https://github.com/tectonic-typesetting/tectonic/blob/b1973f17dbcb930efba57661a4b26edbc1117b7e/tectonic/xetex-linebreak.c#L1995

**Comment by burrbull** [comment]
Another
https://github.com/tectonic-typesetting/tectonic/blob/b1973f17dbcb930efba57661a4b26edbc1117b7e/tectonic/xetex-linebreak.c#L677

**Comment by pkgw** [comment]
Agreed in both cases, good eye!
