### ISSUE TITLE
Do not panic into C/C++ code

### ISSUE THREAD

**Issue by rekka** [tectonic-typesetting/tectonic#63]
It is [undefined behavior to panic from Rust into foreign code](https://doc.rust-lang.org/stable/std/panic/fn.catch_unwind.html) at the moment. Thus the bridge functions in `engines/mod.rs`, etc., should not panic.

At the moment, there are explicit `panic!` invocations for instance [here](https://github.com/tectonic-typesetting/tectonic/blob/328213eff03e652d4c675c2cb9902947bd67aa4f/src/engines/mod.rs#L386) and [here](https://github.com/tectonic-typesetting/tectonic/blob/328213eff03e652d4c675c2cb9902947bd67aa4f/src/engines/mod.rs#L581).

**Comment by pkgw** [comment]
Good catch.
