### ISSUE TITLE
Unable to compile documents with russian language

### ISSUE THREAD

**Issue by SenchoPens** [tectonic-typesetting/tectonic#633]
I get the following error:

```
error: something bad happened inside TeX; its output follows:

===============================================================================
(01.tex
LaTeX2e <2018-04-01> patch level 4
Babel <3.20> and hyphenation patterns for 84 language(s) loaded.
(article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(size10.clo)) (fontenc.sty (t2aenc.def) (t2acmr.fd)

LaTeX Font Warning: Font shape `T2A/lmr/m/n' undefined
(Font)              using `T2A/cmr/m/n' instead on input line 105.

! Font T2A/cmr/m/n/10=larm1000 at 10.0pt not loadable: Metric (TFM) file or ins
talled font not found.
<to be read again>
                   relax
l.105 \fontencoding\encodingdefault\selectfont

No pages of output.
Transcript written on 01.log.
===============================================================================

error: the TeX engine had an unrecoverable error
caused by: halted on potentially-recoverable error as specified
```

Apparently this is happening because larm1000 is missing in the default bundle:
https://github.com/tectonic-typesetting/tectonic/issues/17#issuecomment-305520755
https://github.com/tectonic-typesetting/tectonic/issues/17#issuecomment-305527152

P.S. I don't understand bundles in tectonic; what file do I need to create to state my dependencies and their versions?

**Comment by pkgw** [comment]
@SenchoPens Thanks for reporting! I am building up to updating the default bundle to TeXLive 2020 and we can put this one on the queue of things that can be fixed when it is released.

As for your question about the bundles, it's a good one. The current Tectonic model is that the "bundle" is an archive of a full-featured, self-consistent set of (La)TeX packages from TeXLive. The default bundle aims to be extremely full-featured, but it is always going to miss out on some packages, as you are experiencing here. So there isn't any file where you state your dependencies — instead, Tectonic just pulls down the files it needs as they are requested by the engine. Last I've checked, the TeXLive infrastructure wasn't very rigorous about assigning versions to packages and expressing their interdependencies, which made it infeasible to try to operate in what you might call a "package manager" mode.

I would like to transition to a point where document builds are specified in a sort of `Tectonic.toml` file, analogous to Rust's `Cargo.toml`, and then you could imagine a world where there was more ability to specify extra document dependencies and versions. Unfortunately no one has implemented this concept yet.

**Comment by pkgw** [comment]
I have been working on the TeXLive 2020 update and am returning to this issue. I think that the issue here is that you are trying to load your Cyrillic font using TeX-native fonts, while Tectonic is based on XeTeX and is intended to work with standard Unicode-based OpenType/TrueType fonts.

If you are able to create a Cyrillic document using XeTeX but unable to do so using Tectonic, then that is likely a Tectonic issue. Based on [this StackExchange post](https://tex.stackexchange.com/a/185165/135094), here is a sample that currently works for me:

```
\documentclass{article}

\usepackage[condensed,math]{iwona}
\usepackage[no-math]{fontspec}
\setmainfont[Ligatures=TeX]{IwonaCond-Regular.otf}
\usepackage[russian,english]{babel}

\begin{document}
English.
\textcyrillic{Ломоно́сов}
\end{document}
```

Note that the font names have to be specified as `.otf` file names for Tectonic to be sure of finding them in its bundle.

**Comment by pkgw** [comment]
Closing since I believe this is not a Tectonic bug, just a consequence of using a Unicode-native engine. Please add a comment if you think there's more to investigate here. Thanks!
