### ISSUE TITLE
Accessing a custom style

### ISSUE THREAD

**Issue by edwardabraham** [tectonic-typesetting/tectonic#64]
Excited to have a modern way of running latex, so have just tried giving tectonic a whirl. Immediately hit my first bump. I am using a custom style (.cls) file. When I run xelatex, it can find the style happily. What do I need to do so that tectonic can find the style file? Hopefully just  case of documentation (#62) being required.

**Comment by pkgw** [comment]
The recommended route is to copy the file to place it next to your main `.tex` file. However, there are some issues that crop up if you're running Tectonic from a different directory than the one that the `.tex` file lives in, so this might not work if you do that. Hopefully those issues will be fixed soon.

**Comment by edwardabraham** [comment]
Just, FYI,  we have  a system where we make latex templates and install them using Debian. These days often inside Docker images. Ideally there would be some way of telling tectonic where to find these packages. Or, maybe build them into a custom tectonic bundle... copying them into project directories would feel a bit messy to me.

**Comment by pkgw** [comment]
Yeah, sadly this story has not improved over the past, gulp, year. *In principle* I'd like to recommend that you build your files into a custom bundle, but the infrastructure to support that approach just isn't there at the moment. I'm afraid that for now, copying files is still the most practical approach that I can think of.

**Comment by edwardabraham** [comment]
Thanks so much for your response. Custom bundles sounds like they would
take Tectonic to another level, but yep, the simple approach works too!

**Comment by mnrvwl** [comment]
Yo @edwardabraham, now you can add custom `.sty` files using the `-Z search-path` option that was added in recent versions https://github.com/tectonic-typesetting/tectonic/pull/814

Can you give it a try, come back to tell how did it go and see that we can close this?

**Comment by pkgw** [comment]
It's been a *long* time without followup and we have a variety of similar issues logged, so I'm going to go ahead and close this one.
