### ISSUE TITLE
Unable to install/update tectonic due to cbindgen versions 0.14.4, 0.14.5, and 0.14.6 being yanked

### ISSUE THREAD

**Issue by qtfkwk** [tectonic-typesetting/tectonic#656]
# Error

```
$ cargo install tectonic
    Updating crates.io index
  Installing tectonic v0.1.16
error: failed to compile `tectonic v0.1.16`, intermediate artifacts can be found at `/tmp/cargo-installlLYHdQ`

Caused by:
  failed to select a version for the requirement `cbindgen = "^0.14.4"`
  candidate versions found which didn't match: 0.15.0, 0.14.3, 0.14.2, ...
  location searched: crates.io index
  required by package `tectonic v0.1.16`
```

# Fix

cbingen versions 0.14.4, 0.14.5, and 0.14.6 were yanked; see https://crates.io/crates/cbindgen/versions

Bump cbindgen version to 0.15.0, which [has already been done](https://github.com/tectonic-typesetting/tectonic/commit/f186d765208812b9cc4a98184a15558cd5f1bd6f), but has not been published to crates.io yet.

Workarounds, until the fix is published to crates.io, is to install from the github repo (both of these are working for me):

1. You want the git repo somewhere:

    ```
    git clone https://github.com/tectonic-typesetting/tectonic.git
    cd tectonic
    cargo install --path .
    ```

2. You don't care about the git repo:

    ```
    cargo install --git https://github.com/tectonic-typesetting/tectonic tectonic
    ```

**Comment by pkgw** [comment]
The new release 0.1.17 should fix the issue. Can you please check?

That was ridiculously easy — [Cranko](https://pkgw.github.io/cranko/) FTW!

**Comment by qtfkwk** [comment]
Works perfectly... thanks!
