### ISSUE TITLE
Errors from src/bin/tectonic.rs:inner are shown entirely in "caused by:" lines

### ISSUE THREAD

**Issue by ralismark** [tectonic-typesetting/tectonic#665]
For example, running `echo 'a{' | tectonic -` produces these 3 lines at the end:

```
error:
caused by: the TeX engine had an unrecoverable error
caused by: halted on potentially-recoverable error as specified
```

Notably, the "error:" line has no message, and the actual error is in the first "caused by:" line.

**Comment by pkgw** [comment]
Confirmed, thanks for the easy reproduction example!

**Comment by pkgw** [comment]
Oh, this was introduced in #636:

https://github.com/tectonic-typesetting/tectonic/blob/045dbb5350e6bdb33bbf89d01942add49a1484d4/src/bin/tectonic.rs#L269

Shouldn't be hard to tidy this up.
