### ISSUE TITLE
Support for Revtex 4-2

### ISSUE THREAD

**Issue by appetrosyan** [tectonic-typesetting/tectonic#672]
Whenever I try to compile a document using `revtex4-2`, I can't. It produces an error that `revtex4-2.cls` is not found. This is the up to date APS class and supported by texlive. Currently this is a dealbreaker for me to switch everything to tectonic, vs using plain LaTeX.

**Comment by pkgw** [comment]
I've got good news for you! I am about to flip the switch to update the default bundle to be based on TeXLive 2020.0, which includes revtex4-2. This will happen some time this week or over the weekend.

**Comment by pkgw** [comment]
This should now be enabled! I will close this issue. Please file a new one if needed.

```tex
\documentclass{revtex4-2}

\begin{document}
Hello, world!
\end{document}
```
