### ISSUE TITLE
print BIGGEST_CHAR

### ISSUE THREAD

**Issue by burrbull** [tectonic-typesetting/tectonic#678]
https://github.com/tectonic-typesetting/tectonic/blob/5fbf5be3769ec843ae20353f3f05e0291dbf7c2b/tectonic/xetex-output.c#L250

`s == BIGGEST_CHAR` (0xffff) is not covered here.

I think `s <= BIGGEST_CHAR` should be here.

**Comment by burrbull** [comment]
https://tt.ente.ninja/#/compare/c9e4074e40b17b45338cef8755b39e55ef006b26/af756a69e15ab0acd7234427ac90243e41634ff7

**Comment by pkgw** [comment]
Thanks! I've made this change. (Could also do a `< TOO_BIG_CHAR` ...)
