### ISSUE TITLE
tally increment in print_raw_char

### ISSUE THREAD

**Issue by burrbull** [tectonic-typesetting/tectonic#683]
https://github.com/tectonic-typesetting/tectonic/blob/0f1553e5a82e5ae5bfb7e5986576baaae7c8b490/tectonic/xetex-output.c#L169

I think this should be in PSEUDO selector case only.

cc @pkgw

**Comment by burrbull** [comment]
![изображение](https://user-images.githubusercontent.com/3072754/99553271-03950900-29cf-11eb-9bd7-8487ac8933f0.png)

**Comment by pkgw** [comment]
@burrbull I confess that I don't understand the output portions of the engine well. Is this my mistake in translating the (Xe)TeX code, or is this a mistake in XeTeX itself?

**Comment by pkgw** [comment]
Also, you are warmly invited to submit these issues as pull requests — that way you'll get credit in the Git history.

**Comment by burrbull** [comment]
I see that this is present in original WEB file, so it is definitely not your mistake:
```

no_print: do_nothing;
pseudo: if tally<trick_count then trick_buf[tally mod error_line]:=s;
new_string: begin if pool_ptr<pool_size then append_char(s);
  end; {we drop characters if the string space is full}
othercases write(write_file[selector],xchr[s])
endcases;@/
incr(tally);
exit:end;
```

**Comment by burrbull** [comment]
Probably this is correct behavior (I mean additional spaces). I close issue.

**Comment by pkgw** [comment]
Yeah ... looking at the code, I think you may well be correct, but if the behavior reproduces what's in the original WEB code, I would be extremely reluctant to change it. Thank you for investigating carefully!
