### ISSUE TITLE
Parallelisation

### ISSUE THREAD

**Issue by sirinath** [tectonic-typesetting/tectonic#701]
As many systems now are multi core the code should also be multi threaded as much as possible to utilise all cores.

**Comment by pkgw** [comment]
This is true! It will also be difficult because the TeX engine relies on a massive amount of mutable global state. But it's a good goal to aspire to.

**Comment by sirinath** [comment]
Maybe the architecture can be revisited.

**Comment by sirinath** [comment]
I believe the the best way would be the separation typesetting processing from the font end. The fond end can mimic TeX/LaTeX and translate it into the back end. This way one can have a clean slate typesetting back-end without any legacy or technical debt and also compatibility with TeX/LaTeX for those who want it. The back end can be re used to implement other front ends also.
