### ISSUE TITLE
Yet another bug

### ISSUE THREAD

**Issue by burrbull** [tectonic-typesetting/tectonic#714]
I've found it working on https://github.com/crlf0710/tectonic/pull/339

`xetex-constants.h` contains
https://github.com/tectonic-typesetting/tectonic/blob/e59665718a75fba73a2975165728b767cbfa9342/tectonic/xetex-constants.h#L690-L691

that should be used here:
https://github.com/tectonic-typesetting/tectonic/blob/e59665718a75fba73a2975165728b767cbfa9342/tectonic/xetex-ini.c#L4202-L4203

So those cases are unreachable now:
https://github.com/tectonic-typesetting/tectonic/blob/e59665718a75fba73a2975165728b767cbfa9342/tectonic/xetex-xetex0.c#L2943-L2945

https://github.com/tectonic-typesetting/tectonic/blob/e59665718a75fba73a2975165728b767cbfa9342/tectonic/xetex-xetex0.c#L9585-L9596
and
https://github.com/tectonic-typesetting/tectonic/blob/e59665718a75fba73a2975165728b767cbfa9342/tectonic/xetex-xetex0.c#L9783-L9789

**Comment by pkgw** [comment]
Sorry for the very slow response, but thanks for reporting this! I think it's now fixed. I also think that the relevant code exposes an upstream issue in XeTeX:

https://sourceforge.net/p/xetex/bugs/174/

I believe that I've fixed the issue in Tectonic.
