### ISSUE TITLE
Add a watch mode

### ISSUE THREAD

**Issue by jeffa5** [tectonic-typesetting/tectonic#719]
It would be nice to have the ability to run something like `tectonic -X build --watch` with maybe `-w` for short.

I'd expect this to watch all input files (e.g. working out those from `\input`s) used in compilation and then rebuild when those change.

Probably fits more with the new cargo-like cli.

**Comment by pkgw** [comment]
Yes, this is exactly the sort of elaboration that the new Cargo-like CLI is supposed to help enable! I think a `tectonic watch` would not be at all unreasonable.

**Comment by kpym** [comment]
I want to advocate for this feature. If you combine it with precompiled header (that is recompiled only if it change) this can make XeLaTeX a WYSIWYG ;)
