### ISSUE TITLE
Reverse search fails: paths in .synctex.gz should be absolute

### ISSUE THREAD

**Issue by coxackie** [tectonic-typesetting/tectonic#720]
I was sent to report to you from https://github.com/James-Yu/LaTeX-Workshop/issues/2467. Reverse search fails for VS-code with the LaTeX-Workshop extension , and the problem appears to be that the path created in in .synctex.gz is not absolute.

**Comment by pkgw** [comment]
Thanks for reporting. It seems like it wouldn't be that unreasonable to support relative paths in synctex files, but this should be an easy fix on the Tectonic side.

**Comment by coxackie** [comment]
yeah, to be honest I do not know... I was using reverse search with Zathura and vim and it did work with tectonic output, but maybe Latex-Workshop is more opinionated. At any rate, if it is an easy fix as you say, please consider it.
