### ISSUE TITLE
Correct the documentation to indicate that (ana)conda install works for windows too.

### ISSUE THREAD

**Issue by kpym** [tectonic-typesetting/tectonic#732]
We can read in the documentation section **The Anaconda method** the following

    This method works for Linux and macOS computers.

But it works also very well for Windows (v10.0.19041 + conda 4.9.2) just using the already described instructions. So this will be an easy fix : 

    This method works for Linux, macOS and Windows computers.

And may be point to this method in **Installing Tectonic on Windows** as requested in #483.

**Comment by kpym** [comment]
Just for info. For me the following packages has been installed with tectonic:

```
  cairo              conda-forge/win-64::cairo-1.16.0-hba8bd2f_1007
  fontconfig         conda-forge/win-64::fontconfig-2.13.1-h8289fb6_1003
  gettext            conda-forge/win-64::gettext-0.19.8.1-h1a89ca6_1005
  graphite2          conda-forge/win-64::graphite2-1.3.13-1000
  harfbuzz           conda-forge/win-64::harfbuzz-2.7.4-hc6d2c31_0
  libffi             conda-forge/win-64::libffi-3.3-h0e60522_2
  libglib            conda-forge/win-64::libglib-2.66.4-h5320221_1
  libiconv           conda-forge/win-64::libiconv-1.16-he774522_0
  libxml2            conda-forge/win-64::libxml2-2.9.10-hf5bbc77_3
  pcre               conda-forge/win-64::pcre-8.44-ha925a31_0
  pixman             conda-forge/win-64::pixman-0.40.0-h8ffe710_0
  tectonic           conda-forge/win-64::tectonic-0.4.1-hb5bf743_0
```

**Comment by pkgw** [comment]
The install instructions on the website are a bit old. Here are some newer instructions as I work on bringing the book up to speed:

https://tectonic-typesetting.github.io/book/latest/installation/index.html#pre-built-packages-for-anaconda

Not all of the executables and DLLs listed above are strictly necessary to run Tectonic, but that's the tradeoff you make when you use a package manager. Standalone, statically linked Windows executables are available for download (cf. a different section of the new installation pages).

**Comment by kpym** [comment]
@pkgw Sorry but I was not able to find the information about the statically linked Windows executables. I've checked the book and the github documentation. Could you please point me to the right place. 

I'm very interested in having single statically linked Windows executable.

**Comment by kpym** [comment]
@pkgw I was able to find them in the yesterday's pre-release which introduce the continuous deployment. This is very good news. Having prebuilt binaries for every release is fantastic!

Now you have just to update the documentation ;) 

**Just for info:**

I was not able to run the `gnu` version (`error while loading shared libraries: libicuuc67.dll`).
I was able to run the `msvc` version (`0.4.1+20210114`). I was able to compile a minimal tex file but there were a lot of warnings 
```bash
warning: getc failed
caused by: EOF in getc
```
that are not present when I compile the same code with the conda version of tectonic (`0.4.1`).

**Comment by pkgw** [comment]
@kpym Thanks for the report on the gnu version. It's not statically linked in the same way as the MSVC so I'm not sure if it's actually that useful to publish.

As for the getc warnings, those should have been fixedin #736, which still needs to work its way through the deployment process. About 50% of the time the Windows builds take too long for Azure Pipelines and need to be restarted.

**Comment by kpym** [comment]
@pkgw Just to say that it is not obvious to find the last stable builds in the [Release page](https://github.com/tectonic-typesetting/tectonic/releases) because there are a lot of releases without attached binaries. And it is even not obvious that the release page contains precompiled binaries. It will be nice if in the installation section you put a pointer to the last stable release, which is currently [0.4.1](https://github.com/tectonic-typesetting/tectonic/releases/tag/tectonic%400.4.1). 

Maybe stupid question, but do you really need all these releases without attached binaries ? I say this because we can recover the code from the git repo directly, without using the release page. IMO, the release page is interesting when it contains more than the source code (like binaries or some other compiled assets).

**Comment by pkgw** [comment]
@kpym That's a good point that I hadn't really thought of. My current infrastructure work involves breaking up the code into a lot of sub-projects, and I really like the infrastructure that is underpinning that. But it does mean that the GitHub Releases index gets filled up with a lot of infrastructure entries that aren't "primary" releases of the software. I think that it's useful to log GitHub Releases for the sub-projects, so I'd like to keep doing that, but it does have usability implications. Thanks for pointing that out!

**Comment by pkgw** [comment]
I've tried to tidy this up, with a new magic link

https://tectonic-typesetting.github.io/latest.html

that redirects to the latest release of the main package, skipping all of the sub-crates. I'm going to close this issue now.

Cf. #773 #775 and tectonic-typesetting/tectonic-typesetting.github.io#30
