### ISSUE TITLE
Add V2 compile command to book

### ISSUE THREAD

**Issue by AleSprea97** [tectonic-typesetting/tectonic#735]
Hi, is it possible in Tectonic to compile to pdf an existing LaTeX project with a (possibly complex) custom structure? ( I mean without rewriting it from the start).
If it is possible how it can be done? There is some documentation about it?

**Comment by pkgw** [comment]
Hello,

Yes, Tectonic should be able to compile a wide variety of existing LaTeX projects to PDF. Using the current ("V1") command-line tool, this might be as simple as:

```
tectonic mymainfile.tex
```

Or using the newer "V2" CLI:

```
tectonic -X compile mymainfile.tex
```

(the implementation of this command is virtually identical to the former one).

Tectonic does not support some features such as PostScript output, shell-escape, and `\write18`, which means that not all documents will work.

Does that answer your question?

**Comment by AleSprea97** [comment]
Yes, it does answer my question. I tried both commands and they worked! Thank you!
I'm new to this program, and I'm learning it with the book (https://tectonic-typesetting.github.io/book/latest/index.html).
My question came up because in the book the only commands mentioned were "build" and "new", so I supposed that tectonic could only work with a new document generated by it. 
So I suggest maybe to mention also the  "compile" command in the book.

**Comment by pkgw** [comment]
@AleSprea97 Yes, it's on the to-do list to add the `compile` command in the right place. I'll retitle this issue to be about that.
