### ISSUE TITLE
V2 cli: add external commands

### ISSUE THREAD

**Issue by jeffa5** [tectonic-typesetting/tectonic#737]
Similarly to how cargo searches `PATH` for binaries named `cargo-*` and treats them as subcommands with args passed through it would be cool to have this ability in tectonic, searching for `tectonic-*`, to allow other tools to be created quickly to experiment on new ideas.

**Comment by pkgw** [comment]
Yup. I've got analogous [code in Cranko][xref] that could be used as a template.

[xref]: https://github.com/pkgw/cranko/blob/master/src/main.rs#L831

**Comment by 4e554c4c** [comment]
This issue should be closed, no?
