### ISSUE TITLE
If `shell-escape` is implemented one day, `no-shell-escape` should be also

### ISSUE THREAD

**Issue by kpym** [tectonic-typesetting/tectonic#747]
We can see [in the code](https://github.com/tectonic-typesetting/tectonic/blob/045dbb5350e6bdb33bbf89d01942add49a1484d4/src/unstable_opts.rs#L24-L25) that may be one day `shell-escape` will be implemented. 

I put this issue here to say that `shell-escape` goes together with `no-shell-escape` and if one is implemented, the other should be also.

**Comment by pkgw** [comment]
I can say with high confidence that the default setting will always be to have shell-escape disabled. In that context, do you think that there are use cases where an inverted `no-shell-escape` flag would be useful?

**Comment by kpym** [comment]
IMO, the situation is similar as other tex compilers : we should specify `shell-escape` to use `\write18`, but if we use `no-shell-escape` even with `shell-escape` we can't have system access. In this way if you have in a script `xelatex -no-shell-escale $otherarguments` you are sure that even if `$otherarguments` contains `-shell-escape` the program will stay "secure".

**Comment by pkgw** [comment]
That makes sense. And `-Z shell-escape` is now implemented as of 0.5.0.

**Comment by pkgw** [comment]
Actually I think this should be generalized a bit. In #785 I added a `disable_insecure()` method to the `ProcessingSessionBuilder`, with intended semantics that any kind of insecure feature will be prevented from subsequent activation. We could provide a `--disable-insecure` argument that would not only disable shell-escape, but also turn off any other known-insecure behaviors that might be added in the future.

You could imagine some kind of baroque use case where maybe someone wants to disable Insecure Feature X but *does* want to enable shell-escape, but I think the blanket approach is likely to be what people are seeking 99% of the time.

**Comment by kpym** [comment]
I agree that `-no-shell-escape` is here only for security reasons, so it could be included in `--disable-insecure` without problem. The reasons, which come to my mind, for having both are:
- I have no idea what the other insecure features are, but may be someone would like to disable `shell-escape` and to enable one of this features.
- If `--disable-insecure` is just a shortcut to other `--disable-` and `--no-` flags, it will be clear what `tectonic` consider as "insecure".
- If `--disable-insecure` is a shortcut to other flags, probably the testing will be simpler, because you could test all this flags separately. 
- `--disable-insecure` can always be introduced later, when more than one insecure flags are present, as shortcut.

**Comment by pkgw** [comment]
OK, there is a first draft of this in the 0.6.0 release now: a `--untrusted` option which is the "forcibly-disable-everything-bad-that-we-know-about" option. We can add more variants as the need emerges.
