### ISSUE TITLE
Can't find .xdv if running with absolute path

### ISSUE THREAD

**Issue by h4llow3En** [tectonic-typesetting/tectonic#75]
If you run e.g. `tectonic /Users/you/some/directories/your.tex` you get an
```
error: cannot open "/Users/you/some/directories/your.xdv"
```

Maybe this is the same main issue like in #31

**Comment by pkgw** [comment]
Yes, it is, so I will close this one. Please subscribe to #31 for updates on progress toward solving it — soon, hopefully!
