### ISSUE TITLE
`Read` on uninitialized buffer may cause UB ('tectonic_xdv' crate)

### ISSUE THREAD

**Issue by JOE1994** [tectonic-typesetting/tectonic#752]
Hello :crab:,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description

https://github.com/tectonic-typesetting/tectonic/blob/28a9b4620855871051291928084555ffcc3219f7/crates/xdv/src/lib.rs#L224-L231

`XdvParser::<T>::process()` method creates an uninitialized buffer and passes it to user-provided `Read` implementation. This is unsound, because it allows safe Rust code to exhibit an undefined behavior (read from uninitialized memory).

[This part](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) from the `Read` trait documentation explains the issue:

> It is your responsibility to make sure that `buf` is initialized before calling `read`. Calling read with an uninitialized `buf` (of the kind one obtains via `MaybeUninit<T>`) is not safe, and can lead to undefined behavior.

## How to fix the issue?

The Naive & safe way to fix the issue is to always zero-initialize a buffer before lending it to a user-provided `Read` implementation. Note that this approach will add runtime performance overhead of zero-initializing the buffer.

As of Feb 2021, there is not yet an ideal fix that works with no performance overhead. Below are links to relevant discussions & suggestions for the fix.

* [Rust RFC 2930](https://github.com/rust-lang/rfcs/blob/master/text/2930-read-buf.md#summary)
* [Discussion in Rust Internals Forum](https://internals.rust-lang.org/t/uninitialized-memory/1652)

**Comment by pkgw** [comment]
Thank you for filing this. I've read about this topic since I wrote this code but forgot that I had this implementation in here. I'm looking forward to the day that there's a nicer Rust solution for avoiding this unsoundness issue, but in the meantime, it is totally fine to fix this by zeroing out the buffer. I'll prepare a PR to do so.

**Comment by ammaraskar** [comment]
Has there been a release of `tectonic_xdv` with this fix incorporated? If not, could you make one please. Thank you!

**Comment by pkgw** [comment]
It took a long time, but now there is both a fixed version of `tectonic_xdv` release, and the new 0.5.0 release of `tectonic` is based on that version of the crate.
