### ISSUE TITLE
Migrate engine code to individual crates

### ISSUE THREAD

**Issue by mathemagician98** [tectonic-typesetting/tectonic#756]
My understanding is that engine code seems to be mostly lumped together under the src directory of the main crate, with the exception of the BibTeX engine code, which has its own crate. It would be nice if each engine could have its own crate for modularity. As part of the proposed changes it would also be nice to refactor code to be more consistent with the code found in the `engine_bibtex` crate. For example, renaming the `tex_simple_main` function to `tt_engine_tex_main` and `dvipdfmx_simple_main` to `tt_engine_dvipdfmx_main` might be a good idea for consistency.
(Note: I'm a new contributor to this project, although I have made an effort to acquaint myself somewhat with the source code for this project.)

**Comment by pkgw** [comment]
Welcome! (Apologies for the delay in actually responding — these days I work on Tectonic in intermittent bursts.)

What you describe is definitely the intention for where the architecture should go. In fact it's the main goal I have in mind for the next release of the main package.

**Comment by pkgw** [comment]
#760 has essentially addressed this. I need to take another pass to tidy things up, but the core architecture is now in place.
