### ISSUE TITLE
Build failed on Windows

### ISSUE THREAD

**Issue by D1360-64RC14** [tectonic-typesetting/tectonic#767]
"Full" output:
```
PS X:\tmp\tectonic-master> cargo build --release
   Compiling tectonic_bridge_icu v0.0.0-dev.0 (X:\tmp\tectonic-master\crates\bridge_icu)
   Compiling tectonic_bridge_graphite2 v0.0.0-dev.0 (X:\tmp\tectonic-master\crates\bridge_graphite2)
   Compiling tectonic_bridge_freetype2 v0.0.0-dev.0 (X:\tmp\tectonic-master\crates\bridge_freetype2)
   Compiling rand_core v0.6.2
error: failed to run custom build command for `tectonic_bridge_graphite2 v0.0.0-dev.0 (X:\tmp\tectonic-master\crates\bridge_graphite2)`

Caused by:
  process didn't exit successfully: `X:\tmp\tectonic-master\target\release\build\tectonic_bridge_graphite2-4dcd33dc4a2677ae\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TECTONIC_DEP_BACKEND
  cargo:rerun-if-env-changed=TECTONIC_PKGCONFIG_FORCE_SEMI_STATIC
  cargo:rerun-if-env-changed=GRAPHITE2_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"graphite2\"", cause: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." } }', X:\tmp\tectonic-master\crates\dep_support\src\lib.rs:117:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Obs:
- I'm not on partition C:\
- It's not the first time I execute build (explaining the "full")
- It's already with environment variable `RUST_BACKTRACE=1`

This line changes every time I run build:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"graphite2\"", cause: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." } }', X:\tmp\tectonic-master\crates\dep_support\src\lib.rs:117:14
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"icu-uc\"", cause: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." } }', X:\tmp\tectonic-master\crates\dep_support\src\lib.rs:117:14
```

I liked the project 👍

**Comment by pkgw** [comment]
The issue here is that your build process is failing to find some of the third-party libraries that are required to build Tectonic: these are the `graphite2` and `icu-uc` mentioned in the error reports (apologies that the message isn't easier to parse).

On Windows, I'd recommend trying the [vcpkg]-based build approach, [documented here](https://tectonic-typesetting.github.io/book/latest/howto/build-tectonic/cargo-vcpkg-dep-install.html). On Windows, where `pkg-config` isn't a built-in part of the OS, the vcpkg approach is likely to be more robust.

[vcpkg]: https://github.com/microsoft/vcpkg

**Comment by D1360-64RC14** [comment]
Another error, yay
```
PS X:\tmp\tectonic> cargo vcpkg build
    Fetching vcpkg
    Checkout rev 5a10163c44526b5d42a67480ce7a692a36948761
-- stdout --

-- stderr --
fatal: not a git repository (or any of the parent directories): .git

cargo-vcpkg: failed to execute process
```
```
PS X:\tmp\tectonic> ls -Hidden

    Directory: X:\tmp\tectonic

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d--h--        04/20/2021  04:26 PM                .git

```

**Comment by pkgw** [comment]
Ummm ... hmm. I'm afraid that I have no idea what might be causing that error. It might be good to report that [in the cargo-vcpkg repo][cv] since I don't think that that kind of failure will be specific to Tectonic.

[cv]: https://github.com/mcgoo/vcpkg-rs/issues

In the meantime, maybe try a standalone vcpkg approach?

1. [Install standalone vcpkg](https://docs.microsoft.com/en-us/cpp/build/install-vcpkg?view=msvc-160&tabs=windows)
2. Export appropriate `VCPKG_ROOT` environment variable
3. Install deps: `vcpkg install fontconfig freetype "harfbuzz[icu,graphite2]"`
4. `cargo build` for Tectonic

**Comment by D1360-64RC14** [comment]
I think I know the problem.
I downloaded vcpkg repository using the "Download ZIP" option, but this option doesn't contain the .git folder (because I was just installed Windows and too lazy to install git).
The error message led me to understand that the error was happening on the Tectonic folder.
I'll try again from scratch.

**Comment by D1360-64RC14** [comment]
> I think I know the problem.
> I downloaded vcpkg repository using the "Download ZIP" option, but this option doesn't contain the .git folder (because I was just installed Windows and too lazy to install git).
> The error message led me to understand that the error was happening on the Tectonic folder.
> I'll try again from scratch.

Exacly, this is a requirement of the vcpkg. I **must** clone the repository.

**Comment by D1360-64RC14** [comment]
### Solution
For some reason, the build fails on PowerShell and wosks on CMD.

On the first try, I get this error:
```
error: failed to run custom build command for `tectonic_bridge_harfbuzz v0.0.0-dev.0 (X:\tmp\tectonic\crates\bridge_harfbuzz)`

Caused by:
  process didn't exit successfully: `X:\tmp\tectonic\target\release\build\tectonic_bridge_harfbuzz-a83a713a5e161e1c\build-script-build` (exit code: 1)
  --- stderr
  error: no such file X:\tmp\tectonic\crates\bridge_harfbuzz\harfbuzz\src\harfbuzz.cc
     if you have checked out from Git, you probably need to fetch submodules:
         git submodule update --init
     This is needed because we are attempting to compile a local copy of Harfbuzz.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
As it recommends, I need to run `git submodule update --init`
Then, I rerun `cargo build --release` **and it works!**

```
   ...
   Compiling reqwest v0.11.2
   Compiling tectonic_geturl v0.0.0-dev.0 (X:\tmp\tectonic\crates\geturl)
   Compiling tectonic v0.0.0-dev.0 (X:\tmp\tectonic)
    Finished release [optimized] target(s) in 9m 57s
```

PowerShell, **WHY?** hahaha

**Comment by D1360-64RC14** [comment]
On [Building under Windows](https://tectonic-typesetting.github.io/en-US/contribute.html#building-under-windows) it says:
>In Powershell you will need to set the Variables for the whole terminal session (until the window is closed).
> ```
>set TECTONIC_DEP_BACKEND vcpkg
>set RUSTFLAGS "-Ctarget-feature=+crt-static"
>cargo build --release
>```

But on CMD you must do:
```
set TECTONIC_DEP_BACKEND=vcpkg
set RUSTFLAGS=-Ctarget-feature=+crt-static
cargo build --release
```
(with equal sign and without double quotes or spaces)

**Comment by pkgw** [comment]
I'm glad you got it to work. I'm going to close this issue now.
