### ISSUE TITLE
The "latest release" link in the book's install guide is wrong/confusing

### ISSUE THREAD

**Issue by ijks** [tectonic-typesetting/tectonic#773]
Hi, I was reading the Tectonic book and following the instructions on [this page](https://tectonic-typesetting.github.io/book/latest/installation/index.html), and for the latest pre-built binaries it links to <https://github.com/tectonic-typesetting/tectonic/releases/latest>. However, at the time of writing, the release tagged in GitHub as "latest" is of [`tectonic_bridge_flate`](https://github.com/tectonic-typesetting/tectonic/releases/tag/tectonic_bridge_flate%400.1.1) (and this is what the link leads to); the release for `tectonic` itself is unfortunately not even on the first page of releases, so it took me second to find it. In the meantime I installed using `cargo` (which was thankfully very easy 😄), but this state of affairs could be confusing for people who can't/don't want to use `cargo` or any of the other installation methods.

**Comment by pkgw** [comment]
This should now be fixed after the pull requests above. The magic link

https://tectonic-typesetting.github.io/latest.html

will redirect to the most recent GitHub release of the primary package.
