### ISSUE TITLE
Official Windows executables don't (always?) work -- "side-by-side configuration is incorrect"

### ISSUE THREAD

**Issue by SimonDanisch** [tectonic-typesetting/tectonic#780]
I'm getting:
```
**PS C:\Users\sdani> tectonic.exe --help
Program 'tectonic.exe' failed to run: The application has failed to start because its side-by-side configuration is
incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detailAt line:1
char:1
+ C:\Users\sdani\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ C:\Users\sdani\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed**
```
I guess this is due to some missing C++ redistributable package?
I tried the MSVC and the GNU option.

**Comment by MichaelHatherly** [comment]
Also encountering the same error on a local win10 vm. Interestingly the binaries for windows are running fine in github actions windows runners (https://github.com/MichaelHatherly/Tectonic.jl/runs/2762080655?check_suite_focus=true#step:6:48).

**Comment by pkgw** [comment]
I'm not very experienced with Windows development and I'm afraid that I have no idea what this message means! I will try to look into it, but if there are any Windows developers out there who are more familiar with these matters, please let me know. (That being said, I literally haven't even Googled this issue yet — I have work things that will keep me busy this week.)

If it is related to redistributables, maybe the split into sub-crates has caused some kind of problem with regards to the `crt-static` target flag or items along those lines. It's possible that the act of splitting up all of the build scripts has caused some issues there.

**Comment by B4rtware** [comment]
I also have the same problem. Using `sxstrace.exe` to capture the errors into a log file and converting it to a txt ([mentioned here](https://devblogs.microsoft.com/cesardelatorre/the-application-has-failed-to-start-because-its-side-by-side-configuration-is-incorrect-error-related-to-mmc-exe-programs-and-weird-cause-simple-solution/)) the following error gets displayed:
```
=================
Begin Activation Context Generation.
Input Parameter:
        Flags = 0
        ProcessorArchitecture = AMD64
        CultureFallBacks = en-US;en
        ManifestPath = XXXXXX\tectonic.exe
        AssemblyDirectory = XXXXXXX\
        Application Config File =
-----------------
INFO: Parsing Manifest File XXXXXXX\tectonic.exe.
        INFO: Manifest Definition Identity is Watchexec.Cli.watchexec,type="win32",version="1.15.2.0".
        ERROR: The setting http://schemas.microsoft.com/SMI/2020/WindowsSettings^activeCodePage is not registered.
ERROR: Activation Context generation failed.
End Activation Context Generation.
```
This leads to this issue: https://github.com/watchexec/watchexec/issues/192
Maybe upgrading `watchexec` to a version greater than `1.15.2` will help?

**Comment by pkgw** [comment]
Thank you @B4rtware, excellent sleuthing! My initial investigations suggest that this is indeed the problem. And based on my test runs I think that #782 should fix this problem. I'm not sure if there's a convenient way to update the CI to detect this kind of problem in the future, but I'm very pleased that this appears to be an easy fix! (Knock wood ...)

**Comment by batkiz** [comment]
Tried 0.5.1, but still got the same error. 😢

**Comment by pkgw** [comment]
0.5.1 will still be broken. If all goes well, there will be a 0.5.2 soon that fixes it.

**Comment by MichaelHatherly** [comment]
Latest continuous deployment https://github.com/tectonic-typesetting/tectonic/releases/download/continuous/tectonic-0.5.1+20210608-x86_64-pc-windows-msvc.zip has fixed it for me, thanks.

**Comment by SimonDanisch** [comment]
I can confirm...Thanks for the quick fix :) Would be nice to see an official released binary soon!
