### ISSUE TITLE
Tectonic cannot find `pygmentize`

### ISSUE THREAD

**Issue by jmg-duarte** [tectonic-typesetting/tectonic#784]
Per the title, tectonic cannot find pygmentize even though I have it installed:

```
warning: minted.sty:1186: runsystem(which pygmentize && touch template.aex)...disabled.
error: minted.sty:1186: Package minted Error: You must have `pygmentize' installed to use this package.

See the minted package documentation for explanation.
Type  H <return>  for immediate help
error: halted on potentially-recoverable error as specified
jmgd@kronos ~/D/m/thesis-tex (main) [1]> which pygmentize
/usr/bin/pygmentize
```

**Comment by pkgw** [comment]
The output here is a bit hard to understand. The message ends in `... disabled` indicating that shell-escape has not been enabled in your compilation run. Did you add the `-Z shell-escape` flag to enable shell-escape processing?

**Comment by jmg-duarte** [comment]
I had tried `-shell-escape` but `-Zshell-escape` worked! Thank you
