### ISSUE TITLE
tectonic-bin AUR package does not contain a calculated checksum for i686

### ISSUE THREAD

**Issue by lmartinez-mirror** [tectonic-typesetting/tectonic#789]
A few weeks back I wrote #779 to address a few issues with the PKGBUILD.

However, I noticed the i686 checksum placeholder for tectonic-bin was pushed to the AUR, which will break for i686 users.

Does CI have a label for i686's checksum?

**Comment by pkgw** [comment]
Not right now, but it should be straightforward to add; see the code around here:

https://github.com/tectonic-typesetting/tectonic/blob/master/dist/arch/deploy.sh#L26
