### ISSUE TITLE
Handling large bib files

### ISSUE THREAD

**Issue by tlepoint** [tectonic-typesetting/tectonic#79]
By default, it seems that tectonic does not handle well large bib files.

```
Running BibTeX ...
error: something bad happened inside BibTeX; its output follows:

===============================================================================
Sorry---you've exceeded BibTeX's number of strings 4000
Aborted at line 1707 of file cryptobib/abbrev3.bib
(That was a fatal error)
===============================================================================

error: unspecified fatal bibtex error
```

The bib files are [cryptobib files](https://github.com/cryptobib/)

**Comment by pkgw** [comment]
The fix might be as simple as changing [this line](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/bibtex.c#L140). Anybody up for a pull request?
