### ISSUE TITLE
option for additional file search directories

### ISSUE THREAD

**Issue by japm48** [tectonic-typesetting/tectonic#816]
I have currently several files that override some files to fix the non-UTF-8 issue (#689, files mostly copied from texlive 2021) and I would like to request a feature that allows putting them in a separate directory; this should have lower priority than `cwd` and higher than the bundle files.

Furthermore, I think it would be nice to put my collection of extra sources (preambles, custom classes, etc.) in a different directory without needing to specify the paths in the `.tex` file. This is partially solved by the preamble option in `Tectonic.toml`, but in my use case I would like to repeat this across many similar documents (with different resulting PDFs), so creating a different "project" directory for each one is not scalable.

I hope this can be possible, I tried to skim the sources to send a patch myself and didn't succeed; AFAIK the relevant code relies heavily on the assumption of one root dir + bundle.

**Comment by ralismark** [comment]
There is an in-progress PR #814 to add the ability to specify additional paths to search for files. As is, it'll have the correct priority for this. Also see issue #755.

**Comment by japm48** [comment]
Thanks! Apparently my search skills failed me.
Please mark as duplicate.
