### ISSUE TITLE
Continuous mode

### ISSUE THREAD

**Issue by fourdotfiveg** [tectonic-typesetting/tectonic#82]
Can you implement a continuous mode like `latexmk -pvc`?
It would be really handy

**Comment by rekka** [comment]
I suppose that would be possible, but I am not sure if that is one of the goals of tectonic for now. 

Would something like the following work?

```
watchexec --exts tex tectonic file.tex
```

[`watchexec`](https://github.com/mattgreen/watchexec) might be able to emulate `latexmk -pvc`. Haven't tried this myself, by it looks like a pretty powerful tool.

**Comment by pkgw** [comment]
Yes, I believe that this kind of functionality is outside of the scope of the Tectonic project itself. But this topic has come up several times, so it should be documented; I've added an item for it in #62.
