### ISSUE TITLE
False warning when including JPEGs

### ISSUE THREAD

**Issue by korrat** [tectonic-typesetting/tectonic#821]
While compiling a document containing a JPEG image, I encountered the warning: `JPEG: Invalid data for ResolutionUnit in Exif chunk.` After checking my JPEG, I'm convinced that this warning is false.

After checking the code, I think that [this line](https://github.com/tectonic-typesetting/tectonic/blob/3e6fc3b811e7697056221b118f87bd2395c2ca13/crates/pdf_io/pdf_io/dpx-jpegimage.c#L721) is missing a break, but I'm not sure. Could someone verify this?

**Comment by vlasakm** [comment]
I think you are right. The code is a merge of dvipdfmx's and XeTeX's `jpegimage.c`.

`dvipdfmx` (has this as a middle `case`, has `break`):

```
    switch (tag) {
    [...]
    case JPEG_EXIF_TAG_RESOLUTIONUNIT: // 296
      if (value == 2)
        res_unit = 1.0 ; /* inch */
      else if (value == 3)
        res_unit = 2.54; /* cm */
      break;
    case JPEG_EXIF_TAG_RESUNIT_MS: /* PixelUnit */
    [...]
```

XeTeX (has this as last `case`, no `break`:

```
    switch (tag) {
      [...]
      case 296: /* res unit */
        switch (value) {
          case 2:
            res_unit = 1.0;
            break;
          case 3:
            res_unit = 2.54;
            break;
        }
    }
```

Tectonic (has this as middle `case`, `break` is missing):

```
       switch (tag) {
        [...]
         case JPEG_EXIF_TAG_RESOLUTIONUNIT:
            switch (value) {
            case 2: /* inch */
                res_unit = 1.0;
                break;
            case 3: /* cm */
                res_unit = 2.54;
                break;
            }
        case JPEG_EXIF_TAG_RESUNIT_MS: /* PixelUnit */
        [...]
```

**Comment by pkgw** [comment]
Oh, I always thought that this was just a warning that was over-conservative but got suppressed in normal XeTeX operation! A pull request to fix the behavior here would be very welcome!

**Comment by vlasakm** [comment]
@korrat Can you please send a PR? I don't want to steal your credit, since  you diagnosed the issue. I also don't have setup to confirm the correctness of the fix.

**Comment by pkgw** [comment]
Just to say it: if no one has the time to create a PR, I'm more than happy to do so on your behalf. But I do always like it when people can get credit for their catches in the repo history.
