### ISSUE TITLE
xetex-XeTeXOTMath.cpp is out of date

### ISSUE THREAD

**Issue by davidmjones** [tectonic-typesetting/tectonic#826]
See https://sourceforge.net/p/xetex/bugs/175/

**Comment by vlasakm** [comment]
As of now, the state of XeTeX in Tectonic corresponds to TeX Live 2020 (TeX Live 2020.0, r54631). "Cherry-picking" this change is probably not the right approach. But after the Tectonic sources are updated to match TeX Live 2021, your patch should be included automatically. 

For the update to happen, first update to the [references sources](https://github.com/tectonic-typesetting/tectonic-staging/) is needed, then the real sources in Tectonic have to be updated. This is unfortunately quite an undertaking, and @pkgw has been very busy recently.

**Comment by pkgw** [comment]
Thanks for reporting. And, yes, ideally we would fix this by updating to TL2021. Depending on how much of an effort that is (see tectonic-typesetting/tectonic-staging#17) and how urgent the bugs are, it might be reasonable to cherry-pick these fixes, but I think that life stays a lot simpler if the Tectonic sources correspond to a specific commit of the TeXLive repo, to the extent that we can manage it.

**Comment by mnrvwl** [comment]
ping @davidmjones, is this fixed under `tectonic 0.11.0`?

**Comment by davidmjones** [comment]
Yes, that looks like the right code.  

Apologies for going off on a tangent, but have you given any thought to switching from XeTeX to LuaTeX?  I'm in the process of doing this; if you're interested in discussing it, I'd be happy to open a new issue.

**Comment by mnrvwl** [comment]
@davidmjones See: https://github.com/tectonic-typesetting/tectonic/issues/41#issuecomment-305508631

I feel you, XeTeX is not actively maintained... 😢

**Comment by pkgw** [comment]
Yeah, the short answer is that it would be a big ol' adventure to switch from XeTeX and I personally am really not eager to undertake it at this time. I hold out some hope that Tectonic can maybe even help un-stagnate XeTeX itself, but unfortunately I have not seen any signs of that so far.

As for the specific issue originally raised here, I believe it is now fixed! So I'm going to close this.
