### ISSUE TITLE
`\inputminted` support: files missing from shell-escape working directory

### ISSUE THREAD

**Issue by kwshi** [tectonic-typesetting/tectonic#835]
#708 introduced shell-escape support, which (as motivated in #38) is needed for the exceedingly popular `minted` package for typesetting syntax-highlighted source code.

However, shell-escape support alone is not enough to support `minted`--in particular, the `\inputminted` command does not work correctly.  Here is a simple project demonstrating the issue: [tectonic-minted-test.tar.gz](https://github.com/tectonic-typesetting/tectonic/files/7358064/tectonic-minted-test.tar.gz).  Its contents are:
- `hello.tex`
  ```latex
  \documentclass{article}
  \usepackage{minted}
  \begin{document}
  \inputminted{python}{world.py}
  \end{document}
  ```
- `world.py`
  ```python
  print("hello world")
  ```

When running `tectonic -Z shell-escape` in the above project, the following error is returned:
```
Error: cannot read infile: [Errno 2] No such file or directory: 'world.py'
warning: command exited with error code 1
error: failed to execute the shell-escape command "pygmentize -l python -f latex -P commandprefix=PYG -F tokenmerge -o _minted-hello/72214DB4E1E543018D1BAFE86EA3B444BA1FB043E1554A6696271B99677258E5.pygtex world.py": execution of the request failed
error: hello.tex:4: Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.

See the minted package documentation for explanation.
Type  H <return>  for immediate help
error: halted on potentially-recoverable error as specified
```

After some digging around, I think I've figured the reason for this error.
- Unlike the "original" LaTeX compilers, which run shell-escape commands from the same working directory as the project, Tectonic **runs shell-escape commands from fresh, empty temporary directories** (I checked this by making a blank LaTeX file containing some dummy text and `\write18{pwd}`).
- **Other files in the project directory are not copied over to this temporary directory** (`\write18{ls -l}` shows an empty list).
- As such, when `minted` invokes the `pygmentize` shell command, it tries to load the source file (expecting it to be in the current _project_ working directory) but fails to find it because its working directory is actually set to something like `/tmp/.tmpVGQl7T`.

This being the cause gives rise to a temporary workaround: passing `\inputminted` an _absolute_ rather than relative path makes Tectonic run correctly.

However, I think this workaround is somewhat suboptimal (limits portability of the project/depends on the absolute path of the project; clunky to type; etc.); I think it would be ideal to somehow allow minted to access files from the project directory.

I'm not sure, technically, how this would be done--maybe special-case support, e.g. what Tectonic did for Biber, may be required.  Or maybe there's a simpler solution.  I'm raising this issue because I imagine, given the popularity of `minted`, I must not be the only one facing this trouble.

**Comment by DanySK** [comment]
Hi,
I often use `\write18` to call scripts that scrape the web and prepare LaTeX files, and I can not use absolute paths. I think that it should be possible to configure tectonic to copy over in the temporary directory more files than the core ones, or, maybe better, copy everything.
Alternatively or additionally, it would be nice to have a `-inplace` flag or similar to run into the document folder directly.

I also opened a discussion [here](https://tectonic.newton.cx/t/running-in-place-launching-scripts/306/2).
