### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by NilsIrl** [tectonic-typesetting/tectonic#841]
I'd like to use the version of a package that is not available in the default bundle. What can I do? What can be done?

see: https://tectonic.newton.cx/t/the-texlive-bundle-wasnt-updated-since-2018/245/10?u=nils

**Comment by aterenin** [comment]
+1, I'd like to use the newer `mlmodern` fonts which have a very nice semibold.

**Comment by vlasakm** [comment]
Sorry for not responding earlier, but see my recent description of the tectonic update process: https://github.com/tectonic-typesetting/tectonic-staging/pull/17#issuecomment-973553526.

As updating the bundle shouldn't be _that_ hard, and you can see https://github.com/tectonic-typesetting/tectonic-texlive-bundles, if somebody is offering to help, they should start there.

Actually I think that using the (not yet existing) TeX Live 2021 bundle with XeTeX from 2020 (i.e. current tectonic) might be generally possible, which would unblock TeX Live 2021 for most people.

**Comment by pkgw** [comment]
@vlasakm I think you're right about that a TL2021 bundle with current Tectonic should probably work in a lot of cases. As I mentioned in another comment, producing such a bundle is kind of tedious but not that complicated ... hopefully I'll get the chance to build it sooner rather than later.

**Comment by MJHutchinson** [comment]
+1 would also really like the `mlmodern` font, its super nice for headings and other semibold things

**Comment by mnrvwl** [comment]
Hey @NilsIrl I'm happy to tell you that `siunitx 2022-02-15 v3.0.49` works with `tectonic 0.11.0` as of now 🎉 🎊 🎉
So you can use the usual  `\unit`, `\num{}`, `\qtylist`.

This is a MWE `test.tex`:
```latex
\documentclass{article}
  \usepackage{siunitx}

\begin{document}
  This is a test: \unit{kg.m.s^{-1}}; \num{.12345}; \qtylist{10;30;45}{\metre}
\end{document}
```

Compile it with: `tectonic test.tex`.
Good luck!

**Comment by mnrvwl** [comment]
@aterenin @MJHutchinson Hey I share your love for the `mlmodern` font which works, 2022 brings some great things too and it works for tectonic as of now! Give it a try and let me know how it goes! 💜

MWE test.tex:
```latex
\documentclass{article}
  \usepackage{mlmodern}

\begin{document}
  This is a test.
\end{document}
```

**Comment by pkgw** [comment]
Thanks for following up @mnrvwl!
