### ISSUE TITLE
BibLaTeX bibliography is wiped out by Tectonic 0.8.0

### ISSUE THREAD

**Issue by hpfr** [tectonic-typesetting/tectonic#844]
The Nix package for Tectonic updated recently. I link my bibliography via `\addbibresource{/home/user/absolute/path/main.bib}` and the `biber` integration.

With Tectonic 0.8.0, `tectonic file.tex` turns my bibliography into an empty file, and raw cite keys are output into the document with no bibliography.

Fortunately, my BibLaTeX bibliography file is output from Zotero data with Better BibLaTeX, so nothing was lost. I rolled back to 0.7.0 and it works fine again.

I can't provide example documents at the moment, but I can try later if you think it will help.

cc @marsam @doronbehar because this seems kind of dangerous for users of the Nix package

**Comment by pkgw** [comment]
Yikes, we definitely don't want surprises like this! As a very early guess I wonder if the absolute path to the `main.bib` file is somehow causing a problem.

If anyone is able to construct a simple reproduction case, that would be helpful.

**Comment by gadanidis** [comment]
I experienced the same issue also using an absolute path. Luckily the file was version-controlled so I was able to restore it. I can reproduce it by creating a new document using `tectonic -X new` and adding the following lines to `_preamble.tex`, then running `tectonic -X build`. Whatever bib file is pointed to via the path is wiped.

```latex
\usepackage{biblatex}
\addbibresource{/absolute/path/to/a/bib/file.bib}
```

**Comment by pkgw** [comment]
Thanks @gadanidis! I'm very busy with my day job lately so I'm not sure how promptly I'll get a chance to work on this — if anyone is able to prepare a pull request for this, that would be very welcome.

**Comment by mseri** [comment]
For bisection purposes, do you know if this happens on 0.7.1?

**Comment by hpfr** [comment]
I can't seem to test 0.7.1 because `tectonic -X new` runs into the archive.org URL error fixed by 0.8.0. So now I'm unable to functionally use any version of Tectonic, I guess.

**Comment by hpfr** [comment]
I can't seem to test 0.7.1 because `tectonic -X new` runs into the archive.org URL error fixed by 0.8.0. So now I'm unable to functionally use any version of Tectonic, I guess.

**Comment by hpfr** [comment]
Actually, it looks like a viable workaround is symlinking the bibliography so you can include the relative path to the symlink and avoid an absolute path.

Hopefully no one who isn't backing up their bibliography or generating it from other sources stumbles upon this issue, though.

**Comment by gadanidis** [comment]
A git bisection shows the first troublesome commit is b1c19f39405a5547c852ac493b331c7c015ee8da. It seems to have made some IO-related changes, but I'm not familiar with this codebase and am a bit of a Rust novice so that's as far as I can get right now. If I have time to look into this more I will, but if someone else wants to have a go first please go ahead.

**Comment by pkgw** [comment]
This should be fixed by #868, just merged. My sincere apologies for letting this data-loss issue linger for so long — it's been a hectic few months. I'll update when a new release is made (should be today) to get the fix out into the wild.

**Comment by mseri** [comment]
Thanks a lot!

**Comment by pkgw** [comment]
OK, version 0.8.1 is now out and should fix this issue. I will close this now, but please comment, reopen, or re-file if issues persist!

**Comment by pkgw** [comment]
One quick follow-up: If you happened to have trouble installing version 0.8.1 with `cargo install`, version 0.8.2 should fix the issue.
