### ISSUE TITLE
continuous compilation like `latexmk -pvc`

### ISSUE THREAD

**Issue by LU15W1R7H** [tectonic-typesetting/tectonic#849]
I would like for tectonic to have a continuous compilation mode, like `latexmk -pvc`.
This would make me switch completely to tectonic for my workflow.
But as of today, I can't just save my file in the editor and have tectonic update the output.

**Comment by ratmice** [comment]
for the v2cli there is the command `tectonic -X watch` documented here https://tectonic-typesetting.github.io/book/latest/v2cli/watch.html

**Comment by LU15W1R7H** [comment]
Wow, nice.
Let's see if we can get integration from Vimtex for this!

It would probably be nice if you could say `tectonic -X watch --open` instead of `tectonic -X watch --exec "build --open"`

**Comment by aarmn** [comment]
> It would probably be nice if you could say `tectonic -X watch --open` instead of `tectonic -X watch --exec "build --open"`

I'm working on it in #986, But it would take sometime, also I suggest you to read the discussion there
