### ISSUE TITLE
error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by aspeddro** [tectonic-typesetting/tectonic#853]
```sh
tectonic mono.tex
```

```
Running TeX ...
warning: mono.tex:120: Underfull \hbox (badness 10000) in paragraph at lines 119--120
warning: mono.tex:122: Underfull \hbox (badness 10000) in paragraph at lines 121--122
warning: mono.tex:184: Overfull \hbox (26.98793pt too wide) in paragraph at lines 183--184
Running external tool biber ...
error: No such file or directory (os error 2)
```

```sh
tectonic --version
Tectonic 0.8.0
```

when the following line is commented tectonic works
```tex
\usepackage[style=abnt]{biblatex}
```

OS: Arch Linux
AUR: `paru -S tectonic`

**Comment by LeCyberDucky** [comment]
Hi, 

I just ran into the same issue. I resolved it by installing `biber` via TeX Live:

`tlmgr install biber`

All the other things necessary for compiling get installed automatically, so I'm wondering why `biber` doesn't. In either case, I think a more fleshed out error message would be helpful here. It's not necessarily clear from the error, that the missing file is `biber`.

**Comment by aspeddro** [comment]
Thank you. 

On arch biber is installed with pacman and it works.
