### ISSUE TITLE
pdfpages mishandling files with ".pdf" extension

### ISSUE THREAD

**Issue by KillTheMule** [tectonic-typesetting/tectonic#854]
Hey, while investigating the usage of tectonic in my app, I've come across the following. The problem manifests both the the cli (`tectonic -X compile A3_8Wzw1y.ltx`) as well as the library (via `tectonic::latex_to_pdf`), both on 0.8.0. I'll describe the cli, but if showing the little code from using the library is helpfull, I'll happily show that as well.

So the latex file in question is

```latex
\documentclass{article}
\usepackage{pdfpages}

\begin{document}
\includepdfmerge[pages={4,1,2,3},nup=2x1]{ "ZRS_OPYzxW.pdf"}
\end{document}
```

which fails with the error message

```sh
$tectonic -X compile A3_8Wzw1y.ltx
note: "version 2" Tectonic command-line interface activated
Running TeX ...
error: A3_8Wzw1y.ltx:7: Package pdfpages Error: Page 4 of `"ZRS_O
PYzxW.pdf"' does not exist.

See the pdfpages package documentation for explanation.
Type  H <return>  for immediate help
error: halted on potentially-recoverable error as specified
```

The linked pdf `ZRS_OPYzxW.pdf` definitely has 4 pages, and the error goes away if I just remove the extension `.pdf` from `A3_8Wzw1y.ltx`, and the output looks just as expected. Changing the value of `pages=` inside  `A3_8Wzw1y.ltx` results in different pages being reported as missing, the only thing that works is `pages=1`, which then produces the expected output (but of course not the desired one, because it just includes this one page).

**Comment by mnrvwl** [comment]
Hey @KillTheMule thanks for the time put into this 💜

I'm not able to reproduce it with either `tectonic sample.tex` nor with `tectonic -X compile sample.tex` as of `tectonic 0.11.0`, could you give it a try again and tell me if it doesn't work so we can sort it out?

MWE `sample.tex` used:
```latex
\documentclass{article}
  \usepackage{pdfpages}

\begin{document}
  \includepdfmerge[pages={1},nup=2x1]{"4page.pdf"}
\end{document}
```

**Comment by KillTheMule** [comment]
Yes it still does not work. I downloaded tectonic 0.11 from the releases, and I tried on the following file:

```tex
\documentclass[a3paper,landscape]{article}
\usepackage{pdfpages}

\begin{document}
\includepdfmerge[pages={1,2},nup=2x1=--no-tidy]{ "abc.pdf"}
\end{document}
```

The syntax `\includepdfmerge[nup=2x1=--no-tidy]{"abc.pdf",1,2}` is also allowed but exhibits the same behavior. This all seems to start when using a page index larger than 1, so your example would compile here (but not if using `pages={2}` instead). Here's the error message I'm seeing:

```sh
./tectonic A3_8BjKWO.ltx
Running TeX ...
error: A3_8BjKWO.ltx:7: Package pdfpages Error: Page 2 of `"abc.pdf"' does not exist.

See the pdfpages package documentation for explanation.
Type  H <return>  for immediate help
error: halted on potentially-recoverable error as specified
```

Note that `pdflatex` from the `texlive` package does correctly compile all of the variants.

**Comment by KillTheMule** [comment]
Thanks for investigating! For now, mucking with the documents is out of scope, but I'll keep it in mind for later when I re-investigate using tectonic.

**Comment by Dzordzu** [comment]
Still not working, even with `\graphicx`…
