### ISSUE TITLE
tectonic 0.8.0 fails to load hyperxmp

### ISSUE THREAD

**Issue by efx** [tectonic-typesetting/tectonic#862]
The following document fails to compile.
```tex
\documentclass{report}
\usepackage{hyperxmp}
\begin{document}
hello xmp
\end{document}
```
I saved it as `/tmp/sample.tex` and ran `tectonic /tmp/sample.tex`.
The output was:
```
Running TeX ...
error: hyperxmp.sty:576: Argument of \hyxmp@first@char@i has an extra }
error: halted on potentially-recoverable error as specified
```

I would expect the package to load successfully. I realize this may be an [upstream bug](https://www.ctan.org/tex-archive/macros/latex/contrib/hyperxmp), so feel free to close!

**Comment by pkgw** [comment]
(Sorry for the very long delay to follow up here.)

I think that the newer version might work, or at least will be more straightforward to make work. `\jobname.log` is opened during the processing session before the `hyperxmp` code runs, so the `\filemoddate` command *should* return something useful for it. The `aux` file isn't yet opened by the time we hit this error.

FWIW, the comments in the `\filemoddate` implementation say that it is intentionally expanding to the empty string for nonexistent files, so hopefully that behavior is in fact correct.
