### ISSUE TITLE
Segmentation fault when using `fontspec`

### ISSUE THREAD

**Issue by chloe-the-catgirl** [tectonic-typesetting/tectonic#867]
Hi there,

first of all thanks for all the effort that was put into this project, I really appreciate the effort! Working with TeX has never been easier as far as I can tell! :+1: 

However, with `fontspec` and `\setsansfont`, there seems to be a weird issue resulting in a segmentation fault. The output of my terminal is:

```
$ tectonic invoice.tex                             
Running TeX ...
zsh: segmentation fault (core dumped)  tectonic invoice.tex
```

What I don't understand at all: it worked previously, with the same version. Like, five hours ago it worked, now it doesn't work anymore. At first I thought of something cache-related, but it's reproducible via Docker and another system (GitHub Actions), so the kernel and cache-related stuff can be excluded as well. :confused:

A minimal working example can be found here: https://github.com/chloe-the-catgirl/segmentation-fault-with-tectonic/blob/main/invoice.tex
Curious to see what happens on other people's systems.

### Reproduced with
- tectonic 0.8.0 on Alpine (running inside Docker)
- tectonic 0.8.0 on Arch Linux

**Comment by chloe-the-catgirl** [comment]
I am closing this, it was my fault and my Git LFS setup. Of course, the font files need to be actual fonts, not just pointers to somewhere else.

**Comment by pkgw** [comment]
Phew! But am I interpreting correctly that you can give Tectonic a font-like input that segfaults the engine? Even if the input is "wrong", the engine should never segfault no matter what bogus files you feed into it.

**Comment by chloe-the-catgirl** [comment]
Basically it seems that you can rename any text file to a .ttf/.otf and pass it as a font file. Maybe I still have the repro somewhere, then I’m gonna upload it again ☺️
