### ISSUE TITLE
Error with shade in object

### ISSUE THREAD

**Issue by kpym** [tectonic-typesetting/tectonic#879]
When I compile the folowing code with `xelatex`, there is no problem (the shade region over the blue box is visible) : 
```latex
\documentclass{article}
\usepackage{tikz}
\usepackage[absolute]{textpos}
\begin{document}
%==============================================================
\begin{textblock*}{42mm}[.34,1](28mm,28mm)
\begin{tikzpicture}
  \path[fill=blue] (0,0) rectangle (3,3);
  \path[shade] (1,1) rectangle (2,2);
\end{tikzpicture}
\end{textblock*}

\begin{tikzpicture}
  \path[fill=red] (0,0) rectangle (3,3);
  \path[shade] (1,1) rectangle (2,2);
\end{tikzpicture}
%==============================================================
\end{document}
```
![xe](https://user-images.githubusercontent.com/3142701/160278834-8cabd552-a340-4d29-baaf-0939510f2166.png)

When I compile it with `tectonic` (version 0.8.2 for windows 64), the following error apears : 
```
warning: Error locating image file "pgfshade1"
warning: Specified (image) object doesn't exist: pgfshade1
warning: Interpreting special command uxobj (pdf:) failed.
warning: >> at page="1" position="(3.83574, 662.63)" (in PDF)
warning: >> xxx "pdf:uxobj @pgfshade1"
```
and the shade region over the blue box is not visible.

![tec](https://user-images.githubusercontent.com/3142701/160278871-d084c8fb-acc2-40a3-abf5-9e5c0f966ffa.png)

**Comment by pkgw** [comment]
@kpym Based on the diffs that I've been looking at, I think that's the case? The error message here seems related to some improvements that were added to `xdvipdfmx` in TeXLive 2021, based on the diffs I've been looking at. But if you want to know whether the above example would work in a stock TeXLive 2020 installation, I'd say that you'd just have to try it and see.

**Comment by kpym** [comment]
@pkgw I've checked in Overleaf with TeXLive2021, TeXLive2020, TeXLive2019,... only TeXLive2021 is ok. So this is not specific to tectonic, and you can close this issue, IMO.

Question : Could we specify in tectonic to use old version of TeXLive for compatibility with old scripts ?

**Comment by pkgw** [comment]
> Question : Could we specify in tectonic to use old version of TeXLive for compatibility with old scripts ?

In many cases, you should be able to do this by using an older bundle URL, either specifying it in `Tectonic.toml` (V2) or with a `-w` argument (V1). It is possible that one would *also* need to use an older version of the Tectonic executable to get the older engine implementation, but I think that almost always a newer engine with an older bundle will still work. The changes to the engine over time usually add new features that shouldn't affect older code ... although TeXLive 2021 adds a behavior change that required a change to the `trip` test!
