### ISSUE TITLE
warning: Tectonic does not support `config' special. Ignored.

### ISSUE THREAD

**Issue by Jarmos-san** [tectonic-typesetting/tectonic#904]
I get this warning message each time I invoke the `tectonic -X build` command for compilation. Unfortunately, I couldn't figure out if there's anything wrong with the compiled PDF nor do I see any mention of it anywhere. So, I was wondering why does `tectonic` such a warning? Is it something I should investigate further?

**Comment by pkgw** [comment]
Thanks for asking. This warning has started appearing much more frequently with the upgrade to TeXLive 2021. I haven't dug into things to remind myself what the message is all about, but I'm pretty sure that it does not indicate any significant problems during a build. In which case I think it would make the most sense to just remove the warning.

**Comment by atneit** [comment]
I get this warning alot so I assume you have not removed the warning yet? Is this something you will do? Is there some other way to avoid the warning?

**Comment by vlasakm** [comment]
The handling of the `dvipdfmx:config` special was removed in https://github.com/tectonic-typesetting/tectonic/pull/92.

LaTeX (itself) uses it to request compatibility options in dvipdfmx - e.g. to disable PDF Object streams (which are only in PDF 1.5+, set PDF compression level (useful for debugging and other stuff), set or disable PDF annotation "growth".

The ubiquitous package `hyperref` uses it to change how PDF destinations work - this can be crucial to keep documents "hyperlinkable". E.g. the link to the documentation of this dvipdfmx option is https://texdoc.org/serve/dvipdfmx/0#2d. Notice the anchor, the PDF destination is `2d`, though I didn't check, but presumably this option makes the destination names stable.

All in all, ignoring the `config` special is not the right thing to do.

I added some details and the fix here: https://github.com/tectonic-typesetting/tectonic/pull/953. The support for the `config` special isn't complete and shouldn't be - allowing arbitrary options to be passed shouldn't be allowed. But hopefully should this be enough to eliminate any issues in real world documents.

**Comment by Jarmos-san** [comment]
Looks like @vlasakm is contributing to the project with a potential fix. So, should I reopen this thread until a PR is merged?

**Comment by vlasakm** [comment]
IMO yes, since others will be able find this issue and its status more easily in case they also encounter the warning.

**Comment by pkgw** [comment]
Thanks for investigating @vlasakm! The candidate fix in #953 looks good to me so hopefully this issue will be fixed for real soon.
