### ISSUE TITLE
Undefined control sequence 

### ISSUE THREAD

**Issue by appetrosyan** [tectonic-typesetting/tectonic#912]
It is not possible to compile an MDPI format paper with `tectonic`, while it is possible to compile with `pdflatex`. 

## Expected behaviour

`tectonic supernest.tex` succeeds. 

## Actual
![image](https://user-images.githubusercontent.com/15856657/176407826-b67066ea-1130-4831-b809-927c94fbd718.png)

**Comment by mnrvwl** [comment]
Hey @appetrosyan thx for the issue! 💜
I'm happy to tell you your `supernest.tex` compiles properly with `tectonic 0.11.0` 🎉
Give it a try and come back to me.

**Comment by Neved4** [comment]
@appetrosyan Any news on this?

**Comment by appetrosyan** [comment]
Sorry was snowed under with work. I shall try it in a couple of days.

**Comment by appetrosyan** [comment]
Works! Thank you **very much indeed**
