### ISSUE TITLE
Non-descriptive error for missing \input files

### ISSUE THREAD

**Issue by ilyapopov** [tectonic-typesetting/tectonic#920]
If the input file contains an `\input` macro with a non-existent file

```tex
\input{non-existent.tex}
```

The error message is just:

```
Running TeX ...
error: terminal input forbidden
```

It would be nice if tectonic was more descriptive and also printed the file name that is missing.

**Comment by pkgw** [comment]
Are you running the latest release, and building a document using the latest `tl2021.3r1` bundle? We've added a patch to the LaTeX sources to produce a more helpful error message:

```
error: test.tex:3: ! LaTeX Error: File `nosuchfile.tex' not found.
```

**Comment by ilyapopov** [comment]
I am running the latest master 3428aa5c559e196f2c64273c74e0f69ae0e40ff1

My test input is

```latex
\documentclass[10pt]{article}

\begin{document}
A text
\input{nonexistent.tex}
\end{document}
```
Command line is

    tectonic test.tex

Output is

```
Running TeX ...
error: terminal input forbidden
```

I did not change anything regarding the bundle used. I guess I am using some default one?

**Comment by ilyapopov** [comment]
Ok, so I tried using V2 interface:

```
tectonic -X new
tectonic -X build
```
Running this downloaded a lot of packages, so it seems the newest bundle was not used before. And now I am getting
```
note: "version 2" Tectonic command-line interface activated
Running TeX ...
error: index.tex:2: ! LaTeX Error: File `nonexistent.tex' not found.
error: halted on potentially-recoverable error as specified
```
It look like V1 interface was using an outdated bundle. I could not find instructions how to manage bundles in the documentation.

**Comment by pkgw** [comment]
@ilyapopov does this still seem to be happening? If you have a newer version of Tectonic installed I'm not sure how the V1 interface would be pulling the older code.

**Comment by ilyapopov** [comment]
Sorry for not providing an update.

I have deleted cache at `.cache/Tectonic`, after which tectonic downloaded the newest bundle used that. The problem did not return since then.

**Comment by pkgw** [comment]
Great! Then I'm going to say that this issue is fixed. Thanks for following up!
