### ISSUE TITLE
Adding the ability to process `.tfm` results in failed `test_space`

### ISSUE THREAD

**Issue by mrshu** [tectonic-typesetting/tectonic#95]
As described in #93, when we add the `.tfm` extension to the `format_to_extension` function and thus start to also consider `.tfm` files as `FileFormat::Ofm` files, the `test_space` test fails.

It has therefore been marked with `#[ignore]` in #93, but this situation is certainly not desirable in the long term.

**Comment by pkgw** [comment]
Fixed the relevant underlying bug in #97,although I realized that I was totally wrong it was a bug that this codepath was being triggered!
