### ISSUE TITLE
Ability to specify build targets for `tectonic -X build`

### ISSUE THREAD

**Issue by f-grubm** [tectonic-typesetting/tectonic#970]
I often need to work with projects that require multiple different versions of the generated document, like draft or final version and printed version (with binding correction) or digital version (without binding correction).

As of now (version 0.12.0; Arch Linux) it's possible to create multiple build targets by using multiple `[[output]]` sections, but when I run `tectonic -X build` all of the versions are compiled; running `tectonic -X build --help` doesn't show any way to compile only one of the targets and `tectonic -X build default` leads to an `error: Found argument 'default' which wasn't expected, or isn't valid in this context`. The only quick fix I found was to comment out the target(s) I don't need right now.

It would be nice to be able to tell `tectonic` to only process one specific target (or maybe even multiple specified targets).

**Comment by pkgw** [comment]
Agreed! This is a task that I've intentionally left open as something that should be fairly straightforward for new contributors to implement. The place to look would be the `BuildCommand` struct in the `src/bin/tectonic/v2cli.rs` file.

**Comment by NChechulin** [comment]
I believe the issue should be closed?..
