### ISSUE TITLE
Support for modifying .cache and .config paths 

### ISSUE THREAD

**Issue by karun211** [tectonic-typesetting/tectonic#975]
Hi,

Currently tectonic uses $HOME/.cache and $HOME/.config as default paths. It would be helpful if these paths can be modified with a special flag, especially where home directories are read-only like AWS lambda functions. 

Thanks!

**Comment by mnrvwl** [comment]
An optional flag + environment variables sounds like a great idea! 🚀

**Comment by karun211** [comment]
Actually found the answer looking at the source code, 

Adding them here if anyone else is interested.

export XDG_CONFIG_HOME=
export XDG_CACHE_HOME=

We can close this issue.. I don't need a flag explicitly.
