### ISSUE TITLE
tectonic command not found

### ISSUE THREAD

**Issue by StevE-Ong** [tectonic-typesetting/tectonic#989]
Hi, I installed tectonic using the step 
`curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh`
on my document directory. An executable tectonic was there. I then run tectonic -X build it says the command not found.

> ~/Documents$ curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh
tectonic(drop-installer.sh): downloading version 0.12.0 for architecture x86_64-unknown-linux-gnu
Warning: Not enforcing strong cipher suites for TLS, this is potentially less secure
Warning: Not enforcing TLS v1.2, this is potentially less secure
tectonic(drop-installer.sh): woohoo, the `tectonic` program has been unpacked into the current directory!
tectonic(drop-installer.sh): consider moving it to a directory in $PATH so that it can be run from anywhere
Documents$ tectonic -X build
tectonic: command not found

It should work if we run it in the same directory right? I wonder what is the problem? Thanks

**Comment by pkgw** [comment]
For posterity, I imagine that the solution here is that in most cases one will need to run Tectonic as `./tectonic` in this scenario so that the shell can locate it. For day-to-day running, you need to place the binary into somewhere on your `$PATH`.
