### ISSUE TITLE
Windows release archive format makes the shell installer script not work

### ISSUE THREAD

**Issue by Baldomo** [tectonic-typesetting/tectonic#990]
I opened tectonic-typesetting/tectonic-typesetting.github.io#46 several days ago but there was no answer, so I'm opening an issue here since it also concerns this repository.

While the `drop-installer.sh` correctly detects Bash/MinGW/etc. on Windows, the archive extension is [hardcoded to `.tar.gz`](https://github.com/tectonic-typesetting/tectonic-typesetting.github.io/blob/e38cabbf26639506ceb968eda80adad4f360c939/support/drop-installer.sh#L42), which makes `curl` give a 404. Since Windows should be able to extract Gunzip archives, even with the preinstalled archive manager, I suppose one of the following could be done:
- Change archive extension for the Windows release archive from now on (but it won't work retroactively)
- Change the script so it also sets the archive extension when [detecting the OS type](https://github.com/tectonic-typesetting/tectonic-typesetting.github.io/blob/e38cabbf26639506ceb968eda80adad4f360c939/support/drop-installer.sh#L153), which would probably be easier

**Comment by pkgw** [comment]
Thanks for reporting! I guess that I must not be set up to get GitHub notifications on that other repo, because I didn't get one. Sorry about that. (And I'll try to fix the notification.)

**Comment by Baldomo** [comment]
Sure, thank you! I know Github notifications can be a bit hit and miss to get to work, it's all good. I can work out a PR for the script to hard-code the extension to `.zip` but I'm not sure it's up to me to decide between the two points above, since retroactively changing all archives would break checksums, and changing future release formats could break some workflows (but I guess that would be fine since Tectonic is still `0.x`?).

**Comment by pkgw** [comment]
Thanks for offering! Between those two options, I'd definitely prefer the solution to have the script choose the proper archive extension during OS detection.

I had intended that people would install on Windows using [the PowerShell copy/paste][1], which I believe should work correctly. But there's no reason not to get the bash-based installer working in that context too, for users who have bash+friends available on their Windows systems.

[1]: https://tectonic-typesetting.github.io/book/latest/installation/index.html#copy-paste-a-terminal-command

**Comment by pkgw** [comment]
Also, let's transfer this discussion to https://github.com/tectonic-typesetting/tectonic-typesetting.github.io/issues/46, since any resulting PR will end up going to that repo.
