### ISSUE TITLE
glyphtounicode:7: Undefined control sequence

### ISSUE THREAD

**Issue by NChechulin** [tectonic-typesetting/tectonic#991]
When I first ran `tectonic` on my file (`tectonic main.tex`) a bunch of stuff was downloaded, but then it failed on `glyphtounicode:7`.

I dont see any verbose output option, so this is the only thing I can provide:
```
Running TeX ...
error: glyphtounicode:7: Undefined control sequence
error: halted on potentially-recoverable error as specified
```

Version: 0.12.0

**Comment by vlasakm** [comment]
Some context on the error message: file `glyphtounicode`, line `7`, error `Undefined control sequence` (after looking into `tectonic -X bundle cat glyphtounicode.tex` at line 7, the control sequence is `\pdfglyphtounicode`).

Somehow the file `glyphtounicode.tex` gets included in your document. This is intended for pdf(La)TeX, whereas in general Tectonic is equivalent to Xe(La)TeX. Can you perhaps share [a minimal example](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) or try whether it works with `xelatex` (if you have access to it)? Or even just some share some information about how you use Tectonic - what is this document's context? Is it recent? Does it use old encodings and fonts? Do you want to port it to "modern UTF-8 OpenType XeTeX"? Or are you at least allowed to?

If I had to guess you have a document using old encodings and fonts that you compile with `pdflatex`. I think it is not unreasonable to say that it is not expected to be compilable with Tectonic (XeLaTeX really) out of the box. So next steps would depend on your goals with the document.

**Comment by pkgw** [comment]
Also, the `-p` option will get you the verbose output that will reveal the problematic control sequence. It is unfortunately surprisingly tricky to wire up Tectonic's output processing to get that information in its error message(s).

(BTW, thanks for all of your great replies to people's questions, @vlasakm! I really appreciate it.)
